// Generated by tools/generate_bindings.py from include/photon/photon.h.
// Do not edit: regenerate instead. Every offset below is computed from the
// header and asserted against the C compiler by tests/abi_layout_test.c.
package photon;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;

/**
 * The Photon C ABI, through Panama's foreign function API (JDK 22+).
 *
 * Handles are plain longs and descriptors are {@link MemorySegment}s laid out
 * by the nested layout classes. Arrays are copied by the library during the
 * call, so nothing here has to stay reachable afterwards.
 */
public final class Photon {
    private Photon() {}

    public static final int ABI_VERSION = 1;

    private static final Linker LINKER = Linker.nativeLinker();
    private static final SymbolLookup LOOKUP = loadLibrary();

    private static SymbolLookup loadLibrary() {
        String override = System.getProperty("photon.library");
        Arena arena = Arena.global();
        if (override != null) {
            return SymbolLookup.libraryLookup(java.nio.file.Path.of(override), arena);
        }
        return SymbolLookup.libraryLookup(System.mapLibraryName("photon"), arena);
    }

    private static MethodHandle handle(String name, FunctionDescriptor descriptor) {
        return LINKER.downcallHandle(
            LOOKUP.find(name).orElseThrow(
                () -> new UnsatisfiedLinkError("photon: missing symbol " + name)),
            descriptor);
    }

    // ---- constants ----

    public static final long PH_NULL_HANDLE = 0L;
    public static final int PH_COLOR_AUTO = 0;
    public static final int PH_OK = 0;
    public static final int PH_E_INVALID_HANDLE = -1;
    public static final int PH_E_INVALID_ARGUMENT = -2;
    public static final int PH_E_OUT_OF_MEMORY = -3;
    public static final int PH_E_UNSUPPORTED = -4;
    public static final int PH_E_NOT_INITIALIZED = -5;
    public static final int PH_E_ABI_MISMATCH = -6;
    public static final int PH_E_GL = -7;
    public static final int PH_E_WRONG_THREAD = -8;
    public static final int PH_E_INTERNAL = -9;
    public static final int PH_SCALE_LINEAR = 0;
    public static final int PH_SCALE_LOG = 1;
    public static final int PH_SCALE_TIME = 2;
    public static final int PH_SCALE_CATEGORICAL = 3;
    public static final int PH_SCALE_ORDINAL_TIME = 4;
    public static final int PH_MODE_PAN = 0;
    public static final int PH_MODE_BOX = 1;
    public static final int PH_MODE_BOX_X = 2;
    public static final int PH_MODE_BOX_Y = 3;
    public static final int PH_RENDER_STATIC = 0;
    public static final int PH_RENDER_DYNAMIC = 1;
    public static final int PH_JOIN_ROUND = 0;
    public static final int PH_JOIN_MITER = 1;
    public static final int PH_JOIN_BEVEL = 2;
    public static final int PH_JOIN_BUTT = 3;
    public static final int PH_STEP_NONE = 0;
    public static final int PH_STEP_BEFORE = 1;
    public static final int PH_STEP_AFTER = 2;
    public static final int PH_STEP_CENTER = 3;
    public static final int PH_MARKER_CIRCLE = 0;
    public static final int PH_MARKER_SQUARE = 1;
    public static final int PH_MARKER_TRIANGLE = 2;
    public static final int PH_MARKER_DIAMOND = 3;
    public static final int PH_MARKER_CROSS = 4;
    public static final int PH_MARKER_PLUS = 5;
    public static final int PH_PICK_X = 0;
    public static final int PH_PICK_Y = 1;
    public static final int PH_PICK_XY = 2;
    public static final int PH_THEME_DARK = 0;
    public static final int PH_THEME_LIGHT = 1;
    public static final int PH_GFX_GL33 = 0;
    public static final int PH_GFX_GLES30 = 1;
    public static final int PH_LOG_ERROR = 0;
    public static final int PH_LOG_WARN = 1;
    public static final int PH_LOG_INFO = 2;
    public static final int PH_LOG_DEBUG = 3;
    public static final int PH_TOGGLE_DEFAULT = 0;
    public static final int PH_TOGGLE_ON = 1;
    public static final int PH_TOGGLE_OFF = -1;
    public static final int PH_ORIENT_VERTICAL = 0;
    public static final int PH_ORIENT_HORIZONTAL = 1;
    public static final int PH_EVENT_NONE = 0;
    public static final int PH_EVENT_VIEW_CHANGED = 1;
    public static final int PH_EVENT_CURSOR_MOVED = 2;
    public static final int PH_EVENT_MODE_CHANGED = 3;
    public static final int PH_EVENT_LAYER_VISIBILITY = 4;
    public static final int PH_EVENT_REDRAW_REQUESTED = 5;
    public static final int PH_BUTTON_LEFT = 0;
    public static final int PH_BUTTON_MIDDLE = 1;
    public static final int PH_BUTTON_RIGHT = 2;
    public static final int PH_MOD_NONE = 0;
    public static final int PH_MOD_SHIFT = 1;
    public static final int PH_MOD_CTRL = 2;
    public static final int PH_MOD_ALT = 4;
    public static final int PH_MOD_SUPER = 8;

    // ---- descriptor layouts ----

    /** ph_range — 16 bytes, alignment 8. */
    public static final class ph_range {
        private ph_range() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_DOUBLE.withName("lo"),
            ValueLayout.JAVA_DOUBLE.withName("hi")
        ).withName("ph_range");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_LO = 0L;
        public static final long OFFSET_HI = 8L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_host_desc — 40 bytes, alignment 8. */
    public static final class ph_host_desc {
        private ph_host_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            ValueLayout.JAVA_INT.withName("api"),
            ValueLayout.ADDRESS.withName("get_proc_address"),
            ValueLayout.ADDRESS.withName("get_proc_address_user"),
            ValueLayout.ADDRESS.withName("log"),
            ValueLayout.ADDRESS.withName("log_user")
        ).withName("ph_host_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_API = 4L;
        public static final long OFFSET_GET_PROC_ADDRESS = 8L;
        public static final long OFFSET_GET_PROC_ADDRESS_USER = 16L;
        public static final long OFFSET_LOG = 24L;
        public static final long OFFSET_LOG_USER = 32L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_frame_target — 32 bytes, alignment 4. */
    public static final class ph_frame_target {
        private ph_frame_target() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            ValueLayout.JAVA_INT.withName("framebuffer"),
            ValueLayout.JAVA_INT.withName("x"),
            ValueLayout.JAVA_INT.withName("y"),
            ValueLayout.JAVA_INT.withName("width"),
            ValueLayout.JAVA_INT.withName("height"),
            ValueLayout.JAVA_FLOAT.withName("dpr"),
            ValueLayout.JAVA_INT.withName("flip_y")
        ).withName("ph_frame_target");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_FRAMEBUFFER = 4L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 12L;
        public static final long OFFSET_WIDTH = 16L;
        public static final long OFFSET_HEIGHT = 20L;
        public static final long OFFSET_DPR = 24L;
        public static final long OFFSET_FLIP_Y = 28L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_colormap_spec — 40 bytes, alignment 8. */
    public static final class ph_colormap_spec {
        private ph_colormap_spec() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("stops"),
            ValueLayout.JAVA_INT.withName("stop_count"),
            ValueLayout.JAVA_INT.withName("reverse"),
            ValueLayout.JAVA_INT.withName("discrete_steps"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_colormap_spec");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_NAME = 8L;
        public static final long OFFSET_STOPS = 16L;
        public static final long OFFSET_STOP_COUNT = 24L;
        public static final long OFFSET_REVERSE = 28L;
        public static final long OFFSET_DISCRETE_STEPS = 32L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_margin — 16 bytes, alignment 4. */
    public static final class ph_margin {
        private ph_margin() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_FLOAT.withName("top"),
            ValueLayout.JAVA_FLOAT.withName("right"),
            ValueLayout.JAVA_FLOAT.withName("bottom"),
            ValueLayout.JAVA_FLOAT.withName("left")
        ).withName("ph_margin");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_TOP = 0L;
        public static final long OFFSET_RIGHT = 4L;
        public static final long OFFSET_BOTTOM = 8L;
        public static final long OFFSET_LEFT = 12L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_axis_desc — 56 bytes, alignment 8. */
    public static final class ph_axis_desc {
        private ph_axis_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            ValueLayout.JAVA_INT.withName("type"),
            ph_range.LAYOUT.withName("domain"),
            ValueLayout.ADDRESS.withName("factors"),
            ValueLayout.JAVA_INT.withName("factor_count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("times"),
            ValueLayout.JAVA_INT.withName("time_count"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_axis_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_TYPE = 4L;
        public static final long OFFSET_DOMAIN = 8L;
        public static final long OFFSET_FACTORS = 24L;
        public static final long OFFSET_FACTOR_COUNT = 32L;
        public static final long OFFSET_TIMES = 40L;
        public static final long OFFSET_TIME_COUNT = 48L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_tick — 24 bytes, alignment 8. */
    public static final class ph_tick {
        private ph_tick() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_DOUBLE.withName("value"),
            ValueLayout.ADDRESS.withName("label"),
            ValueLayout.JAVA_INT.withName("minor"),
            ValueLayout.JAVA_INT.withName("grid")
        ).withName("ph_tick");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_VALUE = 0L;
        public static final long OFFSET_LABEL = 8L;
        public static final long OFFSET_MINOR = 16L;
        public static final long OFFSET_GRID = 20L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_axis_config — 104 bytes, alignment 8. */
    public static final class ph_axis_config {
        private ph_axis_config() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            ValueLayout.JAVA_INT.withName("no_axis_line"),
            ValueLayout.JAVA_INT.withName("no_ticks"),
            ValueLayout.JAVA_INT.withName("no_grid"),
            ValueLayout.JAVA_INT.withName("axis_line_color"),
            ValueLayout.JAVA_FLOAT.withName("axis_line_width"),
            ValueLayout.JAVA_INT.withName("tick_color"),
            ValueLayout.JAVA_FLOAT.withName("tick_length"),
            ValueLayout.JAVA_FLOAT.withName("tick_width"),
            ValueLayout.JAVA_INT.withName("label_color"),
            ValueLayout.JAVA_FLOAT.withName("label_size"),
            ValueLayout.JAVA_FLOAT.withName("label_rotation"),
            ValueLayout.JAVA_FLOAT.withName("label_standoff"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("title"),
            ValueLayout.JAVA_INT.withName("title_color"),
            ValueLayout.JAVA_FLOAT.withName("title_size"),
            ValueLayout.JAVA_INT.withName("grid_color"),
            ValueLayout.JAVA_INT.withName("grid_minor_color"),
            ValueLayout.JAVA_FLOAT.withName("grid_width"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("grid_dash"),
            ValueLayout.JAVA_INT.withName("grid_dash_count"),
            ValueLayout.JAVA_INT.withName("minor_ticks")
        ).withName("ph_axis_config");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_NO_AXIS_LINE = 4L;
        public static final long OFFSET_NO_TICKS = 8L;
        public static final long OFFSET_NO_GRID = 12L;
        public static final long OFFSET_AXIS_LINE_COLOR = 16L;
        public static final long OFFSET_AXIS_LINE_WIDTH = 20L;
        public static final long OFFSET_TICK_COLOR = 24L;
        public static final long OFFSET_TICK_LENGTH = 28L;
        public static final long OFFSET_TICK_WIDTH = 32L;
        public static final long OFFSET_LABEL_COLOR = 36L;
        public static final long OFFSET_LABEL_SIZE = 40L;
        public static final long OFFSET_LABEL_ROTATION = 44L;
        public static final long OFFSET_LABEL_STANDOFF = 48L;
        public static final long OFFSET_TITLE = 56L;
        public static final long OFFSET_TITLE_COLOR = 64L;
        public static final long OFFSET_TITLE_SIZE = 68L;
        public static final long OFFSET_GRID_COLOR = 72L;
        public static final long OFFSET_GRID_MINOR_COLOR = 76L;
        public static final long OFFSET_GRID_WIDTH = 80L;
        public static final long OFFSET_GRID_DASH = 88L;
        public static final long OFFSET_GRID_DASH_COUNT = 96L;
        public static final long OFFSET_MINOR_TICKS = 100L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_plot_desc — 200 bytes, alignment 8. */
    public static final class ph_plot_desc {
        private ph_plot_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            ValueLayout.JAVA_INT.withName("width"),
            ValueLayout.JAVA_INT.withName("height"),
            ValueLayout.JAVA_INT.withName("theme"),
            ph_margin.LAYOUT.withName("margin"),
            ph_axis_desc.LAYOUT.withName("x"),
            ph_axis_desc.LAYOUT.withName("y"),
            ValueLayout.JAVA_INT.withName("background"),
            ValueLayout.JAVA_INT.withName("border"),
            ValueLayout.ADDRESS.withName("title"),
            ValueLayout.JAVA_INT.withName("mode"),
            ValueLayout.JAVA_INT.withName("pick"),
            ValueLayout.JAVA_INT.withName("no_interaction"),
            ValueLayout.JAVA_INT.withName("no_hover"),
            ValueLayout.JAVA_INT.withName("no_crosshair"),
            ValueLayout.JAVA_INT.withName("no_colorbar"),
            ValueLayout.JAVA_INT.withName("equal_aspect"),
            ValueLayout.JAVA_INT.withName("bounded_pan"),
            ValueLayout.JAVA_INT.withName("legend"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_plot_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_WIDTH = 4L;
        public static final long OFFSET_HEIGHT = 8L;
        public static final long OFFSET_THEME = 12L;
        public static final long OFFSET_MARGIN = 16L;
        public static final long OFFSET_X = 32L;
        public static final long OFFSET_Y = 88L;
        public static final long OFFSET_BACKGROUND = 144L;
        public static final long OFFSET_BORDER = 148L;
        public static final long OFFSET_TITLE = 152L;
        public static final long OFFSET_MODE = 160L;
        public static final long OFFSET_PICK = 164L;
        public static final long OFFSET_NO_INTERACTION = 168L;
        public static final long OFFSET_NO_HOVER = 172L;
        public static final long OFFSET_NO_CROSSHAIR = 176L;
        public static final long OFFSET_NO_COLORBAR = 180L;
        public static final long OFFSET_EQUAL_ASPECT = 184L;
        public static final long OFFSET_BOUNDED_PAN = 188L;
        public static final long OFFSET_LEGEND = 192L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_line_desc — 96 bytes, alignment 8. */
    public static final class ph_line_desc {
        private ph_line_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.JAVA_FLOAT.withName("width"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("step"),
            ValueLayout.JAVA_INT.withName("join"),
            ValueLayout.JAVA_FLOAT.withName("miter_limit"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("dash"),
            ValueLayout.JAVA_INT.withName("dash_count"),
            ValueLayout.JAVA_INT.withName("no_decimate"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_line_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 16L;
        public static final long OFFSET_COUNT = 24L;
        public static final long OFFSET_COLOR = 28L;
        public static final long OFFSET_WIDTH = 32L;
        public static final long OFFSET_NAME = 40L;
        public static final long OFFSET_Y_AXIS = 48L;
        public static final long OFFSET_STEP = 56L;
        public static final long OFFSET_JOIN = 60L;
        public static final long OFFSET_MITER_LIMIT = 64L;
        public static final long OFFSET_DASH = 72L;
        public static final long OFFSET_DASH_COUNT = 80L;
        public static final long OFFSET_NO_DECIMATE = 84L;
        public static final long OFFSET_RENDER_TYPE = 88L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_scatter_desc — 112 bytes, alignment 8. */
    public static final class ph_scatter_desc {
        private ph_scatter_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.JAVA_FLOAT.withName("size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("sizes"),
            ValueLayout.ADDRESS.withName("colors"),
            ValueLayout.JAVA_INT.withName("marker"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.ADDRESS.withName("color_by"),
            ph_range.LAYOUT.withName("color_by_domain"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_scatter_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 16L;
        public static final long OFFSET_COUNT = 24L;
        public static final long OFFSET_COLOR = 28L;
        public static final long OFFSET_SIZE = 32L;
        public static final long OFFSET_SIZES = 40L;
        public static final long OFFSET_COLORS = 48L;
        public static final long OFFSET_MARKER = 56L;
        public static final long OFFSET_NAME = 64L;
        public static final long OFFSET_Y_AXIS = 72L;
        public static final long OFFSET_COLOR_BY = 80L;
        public static final long OFFSET_COLOR_BY_DOMAIN = 88L;
        public static final long OFFSET_RENDER_TYPE = 104L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_area_desc — 80 bytes, alignment 8. */
    public static final class ph_area_desc {
        private ph_area_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("base"),
            ValueLayout.JAVA_DOUBLE.withName("base_value"),
            ValueLayout.JAVA_INT.withName("color"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_area_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 16L;
        public static final long OFFSET_COUNT = 24L;
        public static final long OFFSET_BASE = 32L;
        public static final long OFFSET_BASE_VALUE = 40L;
        public static final long OFFSET_COLOR = 48L;
        public static final long OFFSET_NAME = 56L;
        public static final long OFFSET_Y_AXIS = 64L;
        public static final long OFFSET_RENDER_TYPE = 72L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_bar_desc — 104 bytes, alignment 8. */
    public static final class ph_bar_desc {
        private ph_bar_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("base"),
            ValueLayout.JAVA_DOUBLE.withName("base_value"),
            ValueLayout.JAVA_DOUBLE.withName("width"),
            ValueLayout.JAVA_DOUBLE.withName("offset"),
            ValueLayout.JAVA_INT.withName("orientation"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.ADDRESS.withName("colors"),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_bar_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 16L;
        public static final long OFFSET_COUNT = 24L;
        public static final long OFFSET_BASE = 32L;
        public static final long OFFSET_BASE_VALUE = 40L;
        public static final long OFFSET_WIDTH = 48L;
        public static final long OFFSET_OFFSET = 56L;
        public static final long OFFSET_ORIENTATION = 64L;
        public static final long OFFSET_COLOR = 68L;
        public static final long OFFSET_COLORS = 72L;
        public static final long OFFSET_NAME = 80L;
        public static final long OFFSET_Y_AXIS = 88L;
        public static final long OFFSET_RENDER_TYPE = 96L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_pie_desc — 96 bytes, alignment 8. */
    public static final class ph_pie_desc {
        private ph_pie_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("values"),
            ValueLayout.JAVA_INT.withName("count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("colors"),
            ValueLayout.JAVA_DOUBLE.withName("center_x"),
            ValueLayout.JAVA_DOUBLE.withName("center_y"),
            ValueLayout.JAVA_DOUBLE.withName("radius"),
            ValueLayout.JAVA_DOUBLE.withName("inner_radius"),
            ValueLayout.JAVA_DOUBLE.withName("start_angle"),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_pie_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_VALUES = 8L;
        public static final long OFFSET_COUNT = 16L;
        public static final long OFFSET_COLORS = 24L;
        public static final long OFFSET_CENTER_X = 32L;
        public static final long OFFSET_CENTER_Y = 40L;
        public static final long OFFSET_RADIUS = 48L;
        public static final long OFFSET_INNER_RADIUS = 56L;
        public static final long OFFSET_START_ANGLE = 64L;
        public static final long OFFSET_NAME = 72L;
        public static final long OFFSET_Y_AXIS = 80L;
        public static final long OFFSET_RENDER_TYPE = 88L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_stem_desc — 80 bytes, alignment 8. */
    public static final class ph_stem_desc {
        private ph_stem_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.JAVA_DOUBLE.withName("baseline"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.JAVA_FLOAT.withName("width"),
            ValueLayout.JAVA_FLOAT.withName("marker_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_stem_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 16L;
        public static final long OFFSET_COUNT = 24L;
        public static final long OFFSET_BASELINE = 32L;
        public static final long OFFSET_COLOR = 40L;
        public static final long OFFSET_WIDTH = 44L;
        public static final long OFFSET_MARKER_SIZE = 48L;
        public static final long OFFSET_NAME = 56L;
        public static final long OFFSET_Y_AXIS = 64L;
        public static final long OFFSET_RENDER_TYPE = 72L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_errorbar_desc — 128 bytes, alignment 8. */
    public static final class ph_errorbar_desc {
        private ph_errorbar_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("y_err_array"),
            ValueLayout.JAVA_DOUBLE.withName("y_err"),
            ValueLayout.ADDRESS.withName("y_err_low_array"),
            ValueLayout.ADDRESS.withName("y_err_high_array"),
            ValueLayout.ADDRESS.withName("x_err_array"),
            ValueLayout.JAVA_DOUBLE.withName("x_err"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.JAVA_FLOAT.withName("width"),
            ValueLayout.JAVA_FLOAT.withName("cap_size"),
            ValueLayout.JAVA_INT.withName("no_whiskers"),
            ValueLayout.JAVA_INT.withName("band"),
            ValueLayout.JAVA_FLOAT.withName("band_opacity"),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_errorbar_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_X = 8L;
        public static final long OFFSET_Y = 16L;
        public static final long OFFSET_COUNT = 24L;
        public static final long OFFSET_Y_ERR_ARRAY = 32L;
        public static final long OFFSET_Y_ERR = 40L;
        public static final long OFFSET_Y_ERR_LOW_ARRAY = 48L;
        public static final long OFFSET_Y_ERR_HIGH_ARRAY = 56L;
        public static final long OFFSET_X_ERR_ARRAY = 64L;
        public static final long OFFSET_X_ERR = 72L;
        public static final long OFFSET_COLOR = 80L;
        public static final long OFFSET_WIDTH = 84L;
        public static final long OFFSET_CAP_SIZE = 88L;
        public static final long OFFSET_NO_WHISKERS = 92L;
        public static final long OFFSET_BAND = 96L;
        public static final long OFFSET_BAND_OPACITY = 100L;
        public static final long OFFSET_NAME = 104L;
        public static final long OFFSET_Y_AXIS = 112L;
        public static final long OFFSET_RENDER_TYPE = 120L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_box_group — 32 bytes, alignment 8. */
    public static final class ph_box_group {
        private ph_box_group() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_DOUBLE.withName("position"),
            ValueLayout.ADDRESS.withName("values"),
            ValueLayout.JAVA_INT.withName("count"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.ADDRESS.withName("label")
        ).withName("ph_box_group");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_POSITION = 0L;
        public static final long OFFSET_VALUES = 8L;
        public static final long OFFSET_COUNT = 16L;
        public static final long OFFSET_COLOR = 20L;
        public static final long OFFSET_LABEL = 24L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_box_desc — 64 bytes, alignment 8. */
    public static final class ph_box_desc {
        private ph_box_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("groups"),
            ValueLayout.JAVA_INT.withName("group_count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.JAVA_DOUBLE.withName("width"),
            ValueLayout.JAVA_INT.withName("no_box"),
            ValueLayout.JAVA_INT.withName("violin"),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_box_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_GROUPS = 8L;
        public static final long OFFSET_GROUP_COUNT = 16L;
        public static final long OFFSET_WIDTH = 24L;
        public static final long OFFSET_NO_BOX = 32L;
        public static final long OFFSET_VIOLIN = 36L;
        public static final long OFFSET_NAME = 40L;
        public static final long OFFSET_Y_AXIS = 48L;
        public static final long OFFSET_RENDER_TYPE = 56L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_heatmap_desc — 112 bytes, alignment 8. */
    public static final class ph_heatmap_desc {
        private ph_heatmap_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("values"),
            ValueLayout.JAVA_INT.withName("cols"),
            ValueLayout.JAVA_INT.withName("rows"),
            ph_range.LAYOUT.withName("x"),
            ph_range.LAYOUT.withName("y"),
            ValueLayout.ADDRESS.withName("colormap"),
            ph_range.LAYOUT.withName("domain"),
            ValueLayout.JAVA_INT.withName("no_smooth"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_heatmap_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_VALUES = 8L;
        public static final long OFFSET_COLS = 16L;
        public static final long OFFSET_ROWS = 20L;
        public static final long OFFSET_X = 24L;
        public static final long OFFSET_Y = 40L;
        public static final long OFFSET_COLORMAP = 56L;
        public static final long OFFSET_DOMAIN = 64L;
        public static final long OFFSET_NO_SMOOTH = 80L;
        public static final long OFFSET_NAME = 88L;
        public static final long OFFSET_Y_AXIS = 96L;
        public static final long OFFSET_RENDER_TYPE = 104L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_image_desc — 96 bytes, alignment 8. */
    public static final class ph_image_desc {
        private ph_image_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("pixels"),
            ValueLayout.JAVA_INT.withName("width"),
            ValueLayout.JAVA_INT.withName("height"),
            ph_range.LAYOUT.withName("x"),
            ph_range.LAYOUT.withName("y"),
            ValueLayout.JAVA_INT.withName("bottom_up"),
            ValueLayout.JAVA_INT.withName("no_smooth"),
            ValueLayout.JAVA_FLOAT.withName("opacity"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_image_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_PIXELS = 8L;
        public static final long OFFSET_WIDTH = 16L;
        public static final long OFFSET_HEIGHT = 20L;
        public static final long OFFSET_X = 24L;
        public static final long OFFSET_Y = 40L;
        public static final long OFFSET_BOTTOM_UP = 56L;
        public static final long OFFSET_NO_SMOOTH = 60L;
        public static final long OFFSET_OPACITY = 64L;
        public static final long OFFSET_NAME = 72L;
        public static final long OFFSET_Y_AXIS = 80L;
        public static final long OFFSET_RENDER_TYPE = 88L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_patch — 40 bytes, alignment 8. */
    public static final class ph_patch {
        private ph_patch() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.ADDRESS.withName("x"),
            ValueLayout.ADDRESS.withName("y"),
            ValueLayout.JAVA_INT.withName("count"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("holes"),
            ValueLayout.JAVA_INT.withName("hole_count"),
            ValueLayout.JAVA_INT.withName("color")
        ).withName("ph_patch");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_X = 0L;
        public static final long OFFSET_Y = 8L;
        public static final long OFFSET_COUNT = 16L;
        public static final long OFFSET_HOLES = 24L;
        public static final long OFFSET_HOLE_COUNT = 32L;
        public static final long OFFSET_COLOR = 36L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_patches_desc — 56 bytes, alignment 8. */
    public static final class ph_patches_desc {
        private ph_patches_desc() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("patches"),
            ValueLayout.JAVA_INT.withName("patch_count"),
            ValueLayout.JAVA_INT.withName("color"),
            ValueLayout.JAVA_FLOAT.withName("opacity"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.ADDRESS.withName("name"),
            ValueLayout.ADDRESS.withName("y_axis"),
            ValueLayout.JAVA_INT.withName("render_type"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_patches_desc");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_PATCHES = 8L;
        public static final long OFFSET_PATCH_COUNT = 16L;
        public static final long OFFSET_COLOR = 20L;
        public static final long OFFSET_OPACITY = 24L;
        public static final long OFFSET_NAME = 32L;
        public static final long OFFSET_Y_AXIS = 40L;
        public static final long OFFSET_RENDER_TYPE = 48L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    /** ph_event — 80 bytes, alignment 8. */
    public static final class ph_event {
        private ph_event() {}

        public static final MemoryLayout LAYOUT = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("struct_size"),
            ValueLayout.JAVA_INT.withName("type"),
            ValueLayout.JAVA_LONG.withName("layer"),
            ph_range.LAYOUT.withName("x"),
            ph_range.LAYOUT.withName("y"),
            ValueLayout.JAVA_DOUBLE.withName("cursor_x"),
            ValueLayout.JAVA_DOUBLE.withName("cursor_y"),
            ValueLayout.JAVA_INT.withName("cursor_valid"),
            ValueLayout.JAVA_INT.withName("mode"),
            ValueLayout.JAVA_INT.withName("visible"),
            MemoryLayout.paddingLayout(4)
        ).withName("ph_event");

        public static final long SIZE = LAYOUT.byteSize();

        public static final long OFFSET_STRUCT_SIZE = 0L;
        public static final long OFFSET_TYPE = 4L;
        public static final long OFFSET_LAYER = 8L;
        public static final long OFFSET_X = 16L;
        public static final long OFFSET_Y = 32L;
        public static final long OFFSET_CURSOR_X = 48L;
        public static final long OFFSET_CURSOR_Y = 56L;
        public static final long OFFSET_CURSOR_VALID = 64L;
        public static final long OFFSET_MODE = 68L;
        public static final long OFFSET_VISIBLE = 72L;

        /** Allocate one, zero-filled — which the ABI defines as all defaults. */
        public static MemorySegment allocate(Arena arena) {
            return arena.allocate(LAYOUT);
        }
    }

    // ---- entry points ----

    /**
     * Every function in the ABI, by name.
     *
     * So that a binding-level test can assert it exercised all of them
     * rather than merely intending to.
     */
    public static final String[] ENTRY_POINTS = {
        "ph_colormap_spec_init",
        "ph_colormap_register",
        "ph_colormap_sample",
        "ph_colormap_count",
        "ph_colormap_name",
        "ph_symmetric_domain",
        "ph_palette_register",
        "ph_palette_count",
        "ph_palette_name",
        "ph_palette_color",
        "ph_abi_version",
        "ph_version",
        "ph_init",
        "ph_shutdown",
        "ph_last_error",
        "ph_color_parse",
        "ph_host_desc_init",
        "ph_frame_target_init",
        "ph_plot_desc_init",
        "ph_axis_desc_init",
        "ph_axis_config_init",
        "ph_line_desc_init",
        "ph_scatter_desc_init",
        "ph_patches_desc_init",
        "ph_area_desc_init",
        "ph_bar_desc_init",
        "ph_pie_desc_init",
        "ph_stem_desc_init",
        "ph_errorbar_desc_init",
        "ph_box_desc_init",
        "ph_heatmap_desc_init",
        "ph_image_desc_init",
        "ph_plot_create",
        "ph_plot_destroy",
        "ph_plot_valid",
        "ph_plot_set_size",
        "ph_plot_set_margin",
        "ph_plot_set_theme",
        "ph_plot_set_title",
        "ph_plot_set_scale",
        "ph_plot_set_domain",
        "ph_plot_get_domain",
        "ph_plot_add_y_axis",
        "ph_plot_remove_y_axis",
        "ph_plot_set_axis_config",
        "ph_plot_set_axis_ticks",
        "ph_plot_autoscale",
        "ph_plot_reset_view",
        "ph_plot_add_line",
        "ph_plot_add_scatter",
        "ph_plot_add_patches",
        "ph_plot_add_area",
        "ph_plot_add_bar",
        "ph_plot_add_pie",
        "ph_plot_add_stem",
        "ph_plot_add_errorbar",
        "ph_plot_add_box",
        "ph_plot_add_heatmap",
        "ph_plot_add_image",
        "ph_layer_set_xy",
        "ph_layer_set_visible",
        "ph_layer_valid",
        "ph_layer_bounds",
        "ph_layer_destroy",
        "ph_plot_set_mode",
        "ph_plot_get_mode",
        "ph_plot_pointer_down",
        "ph_plot_pointer_move",
        "ph_plot_pointer_up",
        "ph_plot_pointer_leave",
        "ph_plot_wheel",
        "ph_plot_pan_pixels",
        "ph_plot_zoom_around",
        "ph_plot_data_at_pixel",
        "ph_plot_pixel_at_data",
        "ph_plot_render",
        "ph_plot_render_pixels",
        "ph_plot_needs_redraw",
        "ph_plot_poll_event",
        "ph_plot_clear_events",
    };

    private static final MethodHandle PH_COLORMAP_SPEC_INIT = handle("ph_colormap_spec_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_COLORMAP_REGISTER = handle("ph_colormap_register", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_COLORMAP_SAMPLE = handle("ph_colormap_sample", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_DOUBLE, ValueLayout.ADDRESS));
    private static final MethodHandle PH_COLORMAP_COUNT = handle("ph_colormap_count", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    private static final MethodHandle PH_COLORMAP_NAME = handle("ph_colormap_name", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_SYMMETRIC_DOMAIN = handle("ph_symmetric_domain", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT, ValueLayout.JAVA_DOUBLE, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PALETTE_REGISTER = handle("ph_palette_register", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PALETTE_COUNT = handle("ph_palette_count", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PALETTE_NAME = handle("ph_palette_name", FunctionDescriptor.of(ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PALETTE_COLOR = handle("ph_palette_color", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_ABI_VERSION = handle("ph_abi_version", FunctionDescriptor.of(ValueLayout.JAVA_INT));
    private static final MethodHandle PH_VERSION = handle("ph_version", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_INIT = handle("ph_init", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.ADDRESS));
    private static final MethodHandle PH_SHUTDOWN = handle("ph_shutdown", FunctionDescriptor.ofVoid());
    private static final MethodHandle PH_LAST_ERROR = handle("ph_last_error", FunctionDescriptor.of(ValueLayout.ADDRESS));
    private static final MethodHandle PH_COLOR_PARSE = handle("ph_color_parse", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_HOST_DESC_INIT = handle("ph_host_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_FRAME_TARGET_INIT = handle("ph_frame_target_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_DESC_INIT = handle("ph_plot_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_AXIS_DESC_INIT = handle("ph_axis_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_AXIS_CONFIG_INIT = handle("ph_axis_config_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_LINE_DESC_INIT = handle("ph_line_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_SCATTER_DESC_INIT = handle("ph_scatter_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_PATCHES_DESC_INIT = handle("ph_patches_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_AREA_DESC_INIT = handle("ph_area_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_BAR_DESC_INIT = handle("ph_bar_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_PIE_DESC_INIT = handle("ph_pie_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_STEM_DESC_INIT = handle("ph_stem_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_ERRORBAR_DESC_INIT = handle("ph_errorbar_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_BOX_DESC_INIT = handle("ph_box_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_HEATMAP_DESC_INIT = handle("ph_heatmap_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_IMAGE_DESC_INIT = handle("ph_image_desc_init", FunctionDescriptor.ofVoid(ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_CREATE = handle("ph_plot_create", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_DESTROY = handle("ph_plot_destroy", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_VALID = handle("ph_plot_valid", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_SET_SIZE = handle("ph_plot_set_size", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_SET_MARGIN = handle("ph_plot_set_margin", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_SET_THEME = handle("ph_plot_set_theme", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_SET_TITLE = handle("ph_plot_set_title", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_SET_SCALE = handle("ph_plot_set_scale", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_SET_DOMAIN = handle("ph_plot_set_domain", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ph_range.LAYOUT));
    private static final MethodHandle PH_PLOT_GET_DOMAIN = handle("ph_plot_get_domain", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_Y_AXIS = handle("ph_plot_add_y_axis", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_REMOVE_Y_AXIS = handle("ph_plot_remove_y_axis", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_SET_AXIS_CONFIG = handle("ph_plot_set_axis_config", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_SET_AXIS_TICKS = handle("ph_plot_set_axis_ticks", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_AUTOSCALE = handle("ph_plot_autoscale", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_RESET_VIEW = handle("ph_plot_reset_view", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_ADD_LINE = handle("ph_plot_add_line", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_SCATTER = handle("ph_plot_add_scatter", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_PATCHES = handle("ph_plot_add_patches", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_AREA = handle("ph_plot_add_area", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_BAR = handle("ph_plot_add_bar", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_PIE = handle("ph_plot_add_pie", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_STEM = handle("ph_plot_add_stem", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_ERRORBAR = handle("ph_plot_add_errorbar", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_BOX = handle("ph_plot_add_box", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_HEATMAP = handle("ph_plot_add_heatmap", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_ADD_IMAGE = handle("ph_plot_add_image", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_LAYER_SET_XY = handle("ph_layer_set_xy", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_LAYER_SET_VISIBLE = handle("ph_layer_set_visible", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_LAYER_VALID = handle("ph_layer_valid", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_LAYER_BOUNDS = handle("ph_layer_bounds", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_LAYER_DESTROY = handle("ph_layer_destroy", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_SET_MODE = handle("ph_plot_set_mode", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_GET_MODE = handle("ph_plot_get_mode", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_POINTER_DOWN = handle("ph_plot_pointer_down", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_POINTER_MOVE = handle("ph_plot_pointer_move", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_POINTER_UP = handle("ph_plot_pointer_up", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_POINTER_LEAVE = handle("ph_plot_pointer_leave", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_WHEEL = handle("ph_plot_wheel", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_PAN_PIXELS = handle("ph_plot_pan_pixels", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE));
    private static final MethodHandle PH_PLOT_ZOOM_AROUND = handle("ph_plot_zoom_around", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE));
    private static final MethodHandle PH_PLOT_DATA_AT_PIXEL = handle("ph_plot_data_at_pixel", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_PIXEL_AT_DATA = handle("ph_plot_pixel_at_data", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_DOUBLE, ValueLayout.JAVA_DOUBLE, ValueLayout.ADDRESS, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_RENDER = handle("ph_plot_render", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_RENDER_PIXELS = handle("ph_plot_render_pixels", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.JAVA_INT, ValueLayout.JAVA_INT, ValueLayout.JAVA_FLOAT, ValueLayout.ADDRESS, ValueLayout.JAVA_INT));
    private static final MethodHandle PH_PLOT_NEEDS_REDRAW = handle("ph_plot_needs_redraw", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));
    private static final MethodHandle PH_PLOT_POLL_EVENT = handle("ph_plot_poll_event", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG, ValueLayout.ADDRESS));
    private static final MethodHandle PH_PLOT_CLEAR_EVENTS = handle("ph_plot_clear_events", FunctionDescriptor.of(ValueLayout.JAVA_INT, ValueLayout.JAVA_LONG));

    public static void ph_colormap_spec_init(MemorySegment out) {
        try {
            PH_COLORMAP_SPEC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_colormap_spec_init failed", photonFailure);
        }
    }

    public static int ph_colormap_register(MemorySegment name, MemorySegment stops, int stop_count) {
        try {
            return (int) PH_COLORMAP_REGISTER.invokeExact(name, stops, stop_count);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_colormap_register failed", photonFailure);
        }
    }

    public static int ph_colormap_sample(MemorySegment spec, double t, MemorySegment out) {
        try {
            return (int) PH_COLORMAP_SAMPLE.invokeExact(spec, t, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_colormap_sample failed", photonFailure);
        }
    }

    public static int ph_colormap_count() {
        try {
            return (int) PH_COLORMAP_COUNT.invokeExact();
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_colormap_count failed", photonFailure);
        }
    }

    public static MemorySegment ph_colormap_name(int index) {
        try {
            return (MemorySegment) PH_COLORMAP_NAME.invokeExact(index);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_colormap_name failed", photonFailure);
        }
    }

    public static int ph_symmetric_domain(MemorySegment values, int count, double center, MemorySegment out) {
        try {
            return (int) PH_SYMMETRIC_DOMAIN.invokeExact(values, count, center, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_symmetric_domain failed", photonFailure);
        }
    }

    public static int ph_palette_register(MemorySegment name, MemorySegment colors, int count) {
        try {
            return (int) PH_PALETTE_REGISTER.invokeExact(name, colors, count);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_palette_register failed", photonFailure);
        }
    }

    public static int ph_palette_count() {
        try {
            return (int) PH_PALETTE_COUNT.invokeExact();
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_palette_count failed", photonFailure);
        }
    }

    public static MemorySegment ph_palette_name(int index) {
        try {
            return (MemorySegment) PH_PALETTE_NAME.invokeExact(index);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_palette_name failed", photonFailure);
        }
    }

    public static int ph_palette_color(MemorySegment name, int index) {
        try {
            return (int) PH_PALETTE_COLOR.invokeExact(name, index);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_palette_color failed", photonFailure);
        }
    }

    public static int ph_abi_version() {
        try {
            return (int) PH_ABI_VERSION.invokeExact();
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_abi_version failed", photonFailure);
        }
    }

    public static void ph_version(MemorySegment major, MemorySegment minor, MemorySegment patch) {
        try {
            PH_VERSION.invokeExact(major, minor, patch);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_version failed", photonFailure);
        }
    }

    public static int ph_init(int abi_version, MemorySegment desc) {
        try {
            return (int) PH_INIT.invokeExact(abi_version, desc);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_init failed", photonFailure);
        }
    }

    public static void ph_shutdown() {
        try {
            PH_SHUTDOWN.invokeExact();
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_shutdown failed", photonFailure);
        }
    }

    public static MemorySegment ph_last_error() {
        try {
            return (MemorySegment) PH_LAST_ERROR.invokeExact();
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_last_error failed", photonFailure);
        }
    }

    public static int ph_color_parse(MemorySegment css, MemorySegment out) {
        try {
            return (int) PH_COLOR_PARSE.invokeExact(css, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_color_parse failed", photonFailure);
        }
    }

    public static void ph_host_desc_init(MemorySegment out) {
        try {
            PH_HOST_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_host_desc_init failed", photonFailure);
        }
    }

    public static void ph_frame_target_init(MemorySegment out) {
        try {
            PH_FRAME_TARGET_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_frame_target_init failed", photonFailure);
        }
    }

    public static void ph_plot_desc_init(MemorySegment out) {
        try {
            PH_PLOT_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_desc_init failed", photonFailure);
        }
    }

    public static void ph_axis_desc_init(MemorySegment out) {
        try {
            PH_AXIS_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_axis_desc_init failed", photonFailure);
        }
    }

    public static void ph_axis_config_init(MemorySegment out) {
        try {
            PH_AXIS_CONFIG_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_axis_config_init failed", photonFailure);
        }
    }

    public static void ph_line_desc_init(MemorySegment out) {
        try {
            PH_LINE_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_line_desc_init failed", photonFailure);
        }
    }

    public static void ph_scatter_desc_init(MemorySegment out) {
        try {
            PH_SCATTER_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_scatter_desc_init failed", photonFailure);
        }
    }

    public static void ph_patches_desc_init(MemorySegment out) {
        try {
            PH_PATCHES_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_patches_desc_init failed", photonFailure);
        }
    }

    public static void ph_area_desc_init(MemorySegment out) {
        try {
            PH_AREA_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_area_desc_init failed", photonFailure);
        }
    }

    public static void ph_bar_desc_init(MemorySegment out) {
        try {
            PH_BAR_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_bar_desc_init failed", photonFailure);
        }
    }

    public static void ph_pie_desc_init(MemorySegment out) {
        try {
            PH_PIE_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_pie_desc_init failed", photonFailure);
        }
    }

    public static void ph_stem_desc_init(MemorySegment out) {
        try {
            PH_STEM_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_stem_desc_init failed", photonFailure);
        }
    }

    public static void ph_errorbar_desc_init(MemorySegment out) {
        try {
            PH_ERRORBAR_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_errorbar_desc_init failed", photonFailure);
        }
    }

    public static void ph_box_desc_init(MemorySegment out) {
        try {
            PH_BOX_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_box_desc_init failed", photonFailure);
        }
    }

    public static void ph_heatmap_desc_init(MemorySegment out) {
        try {
            PH_HEATMAP_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_heatmap_desc_init failed", photonFailure);
        }
    }

    public static void ph_image_desc_init(MemorySegment out) {
        try {
            PH_IMAGE_DESC_INIT.invokeExact(out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_image_desc_init failed", photonFailure);
        }
    }

    public static int ph_plot_create(MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_CREATE.invokeExact(desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_create failed", photonFailure);
        }
    }

    public static int ph_plot_destroy(long plot) {
        try {
            return (int) PH_PLOT_DESTROY.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_destroy failed", photonFailure);
        }
    }

    public static int ph_plot_valid(long plot) {
        try {
            return (int) PH_PLOT_VALID.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_valid failed", photonFailure);
        }
    }

    public static int ph_plot_set_size(long plot, int width, int height) {
        try {
            return (int) PH_PLOT_SET_SIZE.invokeExact(plot, width, height);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_size failed", photonFailure);
        }
    }

    public static int ph_plot_set_margin(long plot, MemorySegment margin) {
        try {
            return (int) PH_PLOT_SET_MARGIN.invokeExact(plot, margin);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_margin failed", photonFailure);
        }
    }

    public static int ph_plot_set_theme(long plot, int theme) {
        try {
            return (int) PH_PLOT_SET_THEME.invokeExact(plot, theme);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_theme failed", photonFailure);
        }
    }

    public static int ph_plot_set_title(long plot, MemorySegment title) {
        try {
            return (int) PH_PLOT_SET_TITLE.invokeExact(plot, title);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_title failed", photonFailure);
        }
    }

    public static int ph_plot_set_scale(long plot, MemorySegment axis, MemorySegment desc) {
        try {
            return (int) PH_PLOT_SET_SCALE.invokeExact(plot, axis, desc);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_scale failed", photonFailure);
        }
    }

    public static int ph_plot_set_domain(long plot, MemorySegment axis, MemorySegment domain) {
        try {
            return (int) PH_PLOT_SET_DOMAIN.invokeExact(plot, axis, domain);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_domain failed", photonFailure);
        }
    }

    public static int ph_plot_get_domain(long plot, MemorySegment axis, MemorySegment out) {
        try {
            return (int) PH_PLOT_GET_DOMAIN.invokeExact(plot, axis, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_get_domain failed", photonFailure);
        }
    }

    public static int ph_plot_add_y_axis(long plot, MemorySegment id, MemorySegment desc, int side) {
        try {
            return (int) PH_PLOT_ADD_Y_AXIS.invokeExact(plot, id, desc, side);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_y_axis failed", photonFailure);
        }
    }

    public static int ph_plot_remove_y_axis(long plot, MemorySegment id) {
        try {
            return (int) PH_PLOT_REMOVE_Y_AXIS.invokeExact(plot, id);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_remove_y_axis failed", photonFailure);
        }
    }

    public static int ph_plot_set_axis_config(long plot, MemorySegment axis, MemorySegment desc) {
        try {
            return (int) PH_PLOT_SET_AXIS_CONFIG.invokeExact(plot, axis, desc);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_axis_config failed", photonFailure);
        }
    }

    public static int ph_plot_set_axis_ticks(long plot, MemorySegment axis, MemorySegment ticks, int count) {
        try {
            return (int) PH_PLOT_SET_AXIS_TICKS.invokeExact(plot, axis, ticks, count);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_axis_ticks failed", photonFailure);
        }
    }

    public static int ph_plot_autoscale(long plot) {
        try {
            return (int) PH_PLOT_AUTOSCALE.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_autoscale failed", photonFailure);
        }
    }

    public static int ph_plot_reset_view(long plot) {
        try {
            return (int) PH_PLOT_RESET_VIEW.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_reset_view failed", photonFailure);
        }
    }

    public static int ph_plot_add_line(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_LINE.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_line failed", photonFailure);
        }
    }

    public static int ph_plot_add_scatter(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_SCATTER.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_scatter failed", photonFailure);
        }
    }

    public static int ph_plot_add_patches(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_PATCHES.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_patches failed", photonFailure);
        }
    }

    public static int ph_plot_add_area(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_AREA.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_area failed", photonFailure);
        }
    }

    public static int ph_plot_add_bar(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_BAR.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_bar failed", photonFailure);
        }
    }

    public static int ph_plot_add_pie(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_PIE.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_pie failed", photonFailure);
        }
    }

    public static int ph_plot_add_stem(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_STEM.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_stem failed", photonFailure);
        }
    }

    public static int ph_plot_add_errorbar(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_ERRORBAR.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_errorbar failed", photonFailure);
        }
    }

    public static int ph_plot_add_box(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_BOX.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_box failed", photonFailure);
        }
    }

    public static int ph_plot_add_heatmap(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_HEATMAP.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_heatmap failed", photonFailure);
        }
    }

    public static int ph_plot_add_image(long plot, MemorySegment desc, MemorySegment out) {
        try {
            return (int) PH_PLOT_ADD_IMAGE.invokeExact(plot, desc, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_add_image failed", photonFailure);
        }
    }

    public static int ph_layer_set_xy(long layer, MemorySegment x, MemorySegment y, int count) {
        try {
            return (int) PH_LAYER_SET_XY.invokeExact(layer, x, y, count);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_layer_set_xy failed", photonFailure);
        }
    }

    public static int ph_layer_set_visible(long layer, int visible) {
        try {
            return (int) PH_LAYER_SET_VISIBLE.invokeExact(layer, visible);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_layer_set_visible failed", photonFailure);
        }
    }

    public static int ph_layer_valid(long layer) {
        try {
            return (int) PH_LAYER_VALID.invokeExact(layer);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_layer_valid failed", photonFailure);
        }
    }

    public static int ph_layer_bounds(long layer, MemorySegment x, MemorySegment y) {
        try {
            return (int) PH_LAYER_BOUNDS.invokeExact(layer, x, y);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_layer_bounds failed", photonFailure);
        }
    }

    public static int ph_layer_destroy(long layer) {
        try {
            return (int) PH_LAYER_DESTROY.invokeExact(layer);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_layer_destroy failed", photonFailure);
        }
    }

    public static int ph_plot_set_mode(long plot, int mode) {
        try {
            return (int) PH_PLOT_SET_MODE.invokeExact(plot, mode);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_set_mode failed", photonFailure);
        }
    }

    public static int ph_plot_get_mode(long plot, MemorySegment out) {
        try {
            return (int) PH_PLOT_GET_MODE.invokeExact(plot, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_get_mode failed", photonFailure);
        }
    }

    public static int ph_plot_pointer_down(long plot, double px, double py, int button, int mods) {
        try {
            return (int) PH_PLOT_POINTER_DOWN.invokeExact(plot, px, py, button, mods);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_pointer_down failed", photonFailure);
        }
    }

    public static int ph_plot_pointer_move(long plot, double px, double py, int mods) {
        try {
            return (int) PH_PLOT_POINTER_MOVE.invokeExact(plot, px, py, mods);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_pointer_move failed", photonFailure);
        }
    }

    public static int ph_plot_pointer_up(long plot, double px, double py, int button, int mods) {
        try {
            return (int) PH_PLOT_POINTER_UP.invokeExact(plot, px, py, button, mods);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_pointer_up failed", photonFailure);
        }
    }

    public static int ph_plot_pointer_leave(long plot) {
        try {
            return (int) PH_PLOT_POINTER_LEAVE.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_pointer_leave failed", photonFailure);
        }
    }

    public static int ph_plot_wheel(long plot, double px, double py, double delta_y, int mods) {
        try {
            return (int) PH_PLOT_WHEEL.invokeExact(plot, px, py, delta_y, mods);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_wheel failed", photonFailure);
        }
    }

    public static int ph_plot_pan_pixels(long plot, double dx, double dy) {
        try {
            return (int) PH_PLOT_PAN_PIXELS.invokeExact(plot, dx, dy);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_pan_pixels failed", photonFailure);
        }
    }

    public static int ph_plot_zoom_around(long plot, double nx, double ny, double factor) {
        try {
            return (int) PH_PLOT_ZOOM_AROUND.invokeExact(plot, nx, ny, factor);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_zoom_around failed", photonFailure);
        }
    }

    public static int ph_plot_data_at_pixel(long plot, double px, double py, MemorySegment out_x, MemorySegment out_y) {
        try {
            return (int) PH_PLOT_DATA_AT_PIXEL.invokeExact(plot, px, py, out_x, out_y);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_data_at_pixel failed", photonFailure);
        }
    }

    public static int ph_plot_pixel_at_data(long plot, double x, double y, MemorySegment out_px, MemorySegment out_py) {
        try {
            return (int) PH_PLOT_PIXEL_AT_DATA.invokeExact(plot, x, y, out_px, out_py);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_pixel_at_data failed", photonFailure);
        }
    }

    public static int ph_plot_render(long plot, MemorySegment target) {
        try {
            return (int) PH_PLOT_RENDER.invokeExact(plot, target);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_render failed", photonFailure);
        }
    }

    public static int ph_plot_render_pixels(long plot, int width, int height, float dpr, MemorySegment out_rgba, int stride_bytes) {
        try {
            return (int) PH_PLOT_RENDER_PIXELS.invokeExact(plot, width, height, dpr, out_rgba, stride_bytes);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_render_pixels failed", photonFailure);
        }
    }

    public static int ph_plot_needs_redraw(long plot) {
        try {
            return (int) PH_PLOT_NEEDS_REDRAW.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_needs_redraw failed", photonFailure);
        }
    }

    public static int ph_plot_poll_event(long plot, MemorySegment out) {
        try {
            return (int) PH_PLOT_POLL_EVENT.invokeExact(plot, out);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_poll_event failed", photonFailure);
        }
    }

    public static int ph_plot_clear_events(long plot) {
        try {
            return (int) PH_PLOT_CLEAR_EVENTS.invokeExact(plot);
        } catch (Throwable photonFailure) {
            throw new AssertionError("photon: ph_plot_clear_events failed", photonFailure);
        }
    }

    /** A `const char*` the ABI returned, or null for NULL. */
    public static String string(MemorySegment text) {
        if (text == null || text.equals(MemorySegment.NULL)) return null;
        return text.reinterpret(Long.MAX_VALUE).getString(0);
    }

    /** The last error on this thread, or an empty string. */
    public static String lastError() {
        MemorySegment message = ph_last_error();
        if (message.equals(MemorySegment.NULL)) return "";
        return message.reinterpret(Long.MAX_VALUE).getString(0);
    }
}
