/*
 * Generated by tools/generate_bindings.py from include/photon/photon.h.
 * Do not edit: regenerate instead.
 *
 * The C# and Java bindings place every field by an offset this generator
 * computed from its own model of the C type system. That model could be
 * wrong, and if it is, nothing in either language would say so — a struct
 * field read at the wrong offset is a plausible-looking number, not a
 * crash. So every offset the generator computed is asserted here against
 * what the compiler actually does, and this file is built as part of the
 * test suite. A wrong model fails the build here rather than corrupting a
 * descriptor in a host months later.
 */

#include <photon/photon.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

/* The rest of the suite builds as C99; this one file needs C11, for
 * _Static_assert and _Alignof. CMake asks for it. */
#if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 201112L
#  error "abi_layout_test.c needs C11"
#endif
#define PH_ASSERT_LAYOUT(cond, message) _Static_assert(cond, message)

/* Every size below assumes a 64-bit target, which is what the bindings
 * assume too. A 32-bit build would need its own generated pair. */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFu

PH_ASSERT_LAYOUT(sizeof(ph_range) == 16, "ph_range size");
PH_ASSERT_LAYOUT(_Alignof(ph_range) == 8, "ph_range alignment");
PH_ASSERT_LAYOUT(offsetof(ph_range, lo) == 0, "ph_range.lo offset");
PH_ASSERT_LAYOUT(offsetof(ph_range, hi) == 8, "ph_range.hi offset");

PH_ASSERT_LAYOUT(sizeof(ph_host_desc) == 40, "ph_host_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_host_desc) == 8, "ph_host_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, struct_size) == 0, "ph_host_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, api) == 4, "ph_host_desc.api offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, get_proc_address) == 8, "ph_host_desc.get_proc_address offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, get_proc_address_user) == 16, "ph_host_desc.get_proc_address_user offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, log) == 24, "ph_host_desc.log offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, log_user) == 32, "ph_host_desc.log_user offset");

PH_ASSERT_LAYOUT(sizeof(ph_frame_target) == 32, "ph_frame_target size");
PH_ASSERT_LAYOUT(_Alignof(ph_frame_target) == 4, "ph_frame_target alignment");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, struct_size) == 0, "ph_frame_target.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, framebuffer) == 4, "ph_frame_target.framebuffer offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, x) == 8, "ph_frame_target.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, y) == 12, "ph_frame_target.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, width) == 16, "ph_frame_target.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, height) == 20, "ph_frame_target.height offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, dpr) == 24, "ph_frame_target.dpr offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, flip_y) == 28, "ph_frame_target.flip_y offset");

PH_ASSERT_LAYOUT(sizeof(ph_colormap_spec) == 40, "ph_colormap_spec size");
PH_ASSERT_LAYOUT(_Alignof(ph_colormap_spec) == 8, "ph_colormap_spec alignment");
PH_ASSERT_LAYOUT(offsetof(ph_colormap_spec, struct_size) == 0, "ph_colormap_spec.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_colormap_spec, name) == 8, "ph_colormap_spec.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_colormap_spec, stops) == 16, "ph_colormap_spec.stops offset");
PH_ASSERT_LAYOUT(offsetof(ph_colormap_spec, stop_count) == 24, "ph_colormap_spec.stop_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_colormap_spec, reverse) == 28, "ph_colormap_spec.reverse offset");
PH_ASSERT_LAYOUT(offsetof(ph_colormap_spec, discrete_steps) == 32, "ph_colormap_spec.discrete_steps offset");

PH_ASSERT_LAYOUT(sizeof(ph_polar_config) == 40, "ph_polar_config size");
PH_ASSERT_LAYOUT(_Alignof(ph_polar_config) == 8, "ph_polar_config alignment");
PH_ASSERT_LAYOUT(offsetof(ph_polar_config, struct_size) == 0, "ph_polar_config.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_config, enabled) == 4, "ph_polar_config.enabled offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_config, degrees) == 8, "ph_polar_config.degrees offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_config, max_radius) == 16, "ph_polar_config.max_radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_config, rotation) == 24, "ph_polar_config.rotation offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_config, spoke_step) == 32, "ph_polar_config.spoke_step offset");

PH_ASSERT_LAYOUT(sizeof(ph_polar_line_desc) == 72, "ph_polar_line_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_polar_line_desc) == 8, "ph_polar_line_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, struct_size) == 0, "ph_polar_line_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, theta) == 8, "ph_polar_line_desc.theta offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, r) == 16, "ph_polar_line_desc.r offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, count) == 24, "ph_polar_line_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, color) == 28, "ph_polar_line_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, width) == 32, "ph_polar_line_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, closed) == 36, "ph_polar_line_desc.closed offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, dash) == 40, "ph_polar_line_desc.dash offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, dash_count) == 48, "ph_polar_line_desc.dash_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, name) == 56, "ph_polar_line_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_line_desc, render_type) == 64, "ph_polar_line_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_polar_scatter_desc) == 80, "ph_polar_scatter_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_polar_scatter_desc) == 8, "ph_polar_scatter_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, struct_size) == 0, "ph_polar_scatter_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, theta) == 8, "ph_polar_scatter_desc.theta offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, r) == 16, "ph_polar_scatter_desc.r offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, count) == 24, "ph_polar_scatter_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, color) == 28, "ph_polar_scatter_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, size) == 32, "ph_polar_scatter_desc.size offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, sizes) == 40, "ph_polar_scatter_desc.sizes offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, colors) == 48, "ph_polar_scatter_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, marker) == 56, "ph_polar_scatter_desc.marker offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, name) == 64, "ph_polar_scatter_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_polar_scatter_desc, render_type) == 72, "ph_polar_scatter_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_pivot_levels) == 56, "ph_pivot_levels size");
PH_ASSERT_LAYOUT(_Alignof(ph_pivot_levels) == 8, "ph_pivot_levels alignment");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, pivot) == 0, "ph_pivot_levels.pivot offset");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, r1) == 8, "ph_pivot_levels.r1 offset");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, r2) == 16, "ph_pivot_levels.r2 offset");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, r3) == 24, "ph_pivot_levels.r3 offset");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, s1) == 32, "ph_pivot_levels.s1 offset");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, s2) == 40, "ph_pivot_levels.s2 offset");
PH_ASSERT_LAYOUT(offsetof(ph_pivot_levels, s3) == 48, "ph_pivot_levels.s3 offset");

PH_ASSERT_LAYOUT(sizeof(ph_brick) == 24, "ph_brick size");
PH_ASSERT_LAYOUT(_Alignof(ph_brick) == 8, "ph_brick alignment");
PH_ASSERT_LAYOUT(offsetof(ph_brick, open) == 0, "ph_brick.open offset");
PH_ASSERT_LAYOUT(offsetof(ph_brick, close) == 8, "ph_brick.close offset");
PH_ASSERT_LAYOUT(offsetof(ph_brick, x) == 16, "ph_brick.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_brick, up) == 20, "ph_brick.up offset");

PH_ASSERT_LAYOUT(sizeof(ph_pf_column) == 24, "ph_pf_column size");
PH_ASSERT_LAYOUT(_Alignof(ph_pf_column) == 8, "ph_pf_column alignment");
PH_ASSERT_LAYOUT(offsetof(ph_pf_column, from) == 0, "ph_pf_column.from offset");
PH_ASSERT_LAYOUT(offsetof(ph_pf_column, to) == 8, "ph_pf_column.to offset");
PH_ASSERT_LAYOUT(offsetof(ph_pf_column, col) == 16, "ph_pf_column.col offset");
PH_ASSERT_LAYOUT(offsetof(ph_pf_column, kind) == 20, "ph_pf_column.kind offset");

PH_ASSERT_LAYOUT(sizeof(ph_volume_profile) == 32, "ph_volume_profile size");
PH_ASSERT_LAYOUT(_Alignof(ph_volume_profile) == 8, "ph_volume_profile alignment");
PH_ASSERT_LAYOUT(offsetof(ph_volume_profile, bin_size) == 0, "ph_volume_profile.bin_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_volume_profile, price_min) == 8, "ph_volume_profile.price_min offset");
PH_ASSERT_LAYOUT(offsetof(ph_volume_profile, price_max) == 16, "ph_volume_profile.price_max offset");
PH_ASSERT_LAYOUT(offsetof(ph_volume_profile, poc_index) == 24, "ph_volume_profile.poc_index offset");

PH_ASSERT_LAYOUT(sizeof(ph_drawdown) == 16, "ph_drawdown size");
PH_ASSERT_LAYOUT(_Alignof(ph_drawdown) == 8, "ph_drawdown alignment");
PH_ASSERT_LAYOUT(offsetof(ph_drawdown, max_drawdown) == 0, "ph_drawdown.max_drawdown offset");
PH_ASSERT_LAYOUT(offsetof(ph_drawdown, trough_index) == 8, "ph_drawdown.trough_index offset");
PH_ASSERT_LAYOUT(offsetof(ph_drawdown, peak_index) == 12, "ph_drawdown.peak_index offset");

PH_ASSERT_LAYOUT(sizeof(ph_grid_info) == 40, "ph_grid_info size");
PH_ASSERT_LAYOUT(_Alignof(ph_grid_info) == 8, "ph_grid_info alignment");
PH_ASSERT_LAYOUT(offsetof(ph_grid_info, cols) == 0, "ph_grid_info.cols offset");
PH_ASSERT_LAYOUT(offsetof(ph_grid_info, rows) == 4, "ph_grid_info.rows offset");
PH_ASSERT_LAYOUT(offsetof(ph_grid_info, x) == 8, "ph_grid_info.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_grid_info, y) == 24, "ph_grid_info.y offset");

PH_ASSERT_LAYOUT(sizeof(ph_box_stats) == 64, "ph_box_stats size");
PH_ASSERT_LAYOUT(_Alignof(ph_box_stats) == 8, "ph_box_stats alignment");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, min) == 0, "ph_box_stats.min offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, q1) == 8, "ph_box_stats.q1 offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, median) == 16, "ph_box_stats.median offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, q3) == 24, "ph_box_stats.q3 offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, max) == 32, "ph_box_stats.max offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, whisker_lo) == 40, "ph_box_stats.whisker_lo offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, whisker_hi) == 48, "ph_box_stats.whisker_hi offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, outlier_count) == 56, "ph_box_stats.outlier_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_stats, valid) == 60, "ph_box_stats.valid offset");

PH_ASSERT_LAYOUT(sizeof(ph_linear_fit) == 40, "ph_linear_fit size");
PH_ASSERT_LAYOUT(_Alignof(ph_linear_fit) == 8, "ph_linear_fit alignment");
PH_ASSERT_LAYOUT(offsetof(ph_linear_fit, slope) == 0, "ph_linear_fit.slope offset");
PH_ASSERT_LAYOUT(offsetof(ph_linear_fit, intercept) == 8, "ph_linear_fit.intercept offset");
PH_ASSERT_LAYOUT(offsetof(ph_linear_fit, r2) == 16, "ph_linear_fit.r2 offset");
PH_ASSERT_LAYOUT(offsetof(ph_linear_fit, stderror) == 24, "ph_linear_fit.stderror offset");
PH_ASSERT_LAYOUT(offsetof(ph_linear_fit, n) == 32, "ph_linear_fit.n offset");

PH_ASSERT_LAYOUT(sizeof(ph_regression_metrics) == 32, "ph_regression_metrics size");
PH_ASSERT_LAYOUT(_Alignof(ph_regression_metrics) == 8, "ph_regression_metrics alignment");
PH_ASSERT_LAYOUT(offsetof(ph_regression_metrics, mse) == 0, "ph_regression_metrics.mse offset");
PH_ASSERT_LAYOUT(offsetof(ph_regression_metrics, rmse) == 8, "ph_regression_metrics.rmse offset");
PH_ASSERT_LAYOUT(offsetof(ph_regression_metrics, mae) == 16, "ph_regression_metrics.mae offset");
PH_ASSERT_LAYOUT(offsetof(ph_regression_metrics, r2) == 24, "ph_regression_metrics.r2 offset");

PH_ASSERT_LAYOUT(sizeof(ph_class_score) == 40, "ph_class_score size");
PH_ASSERT_LAYOUT(_Alignof(ph_class_score) == 8, "ph_class_score alignment");
PH_ASSERT_LAYOUT(offsetof(ph_class_score, precision) == 0, "ph_class_score.precision offset");
PH_ASSERT_LAYOUT(offsetof(ph_class_score, recall) == 8, "ph_class_score.recall offset");
PH_ASSERT_LAYOUT(offsetof(ph_class_score, f1) == 16, "ph_class_score.f1 offset");
PH_ASSERT_LAYOUT(offsetof(ph_class_score, support) == 24, "ph_class_score.support offset");
PH_ASSERT_LAYOUT(offsetof(ph_class_score, label) == 32, "ph_class_score.label offset");

PH_ASSERT_LAYOUT(sizeof(ph_class_average) == 24, "ph_class_average size");
PH_ASSERT_LAYOUT(_Alignof(ph_class_average) == 8, "ph_class_average alignment");
PH_ASSERT_LAYOUT(offsetof(ph_class_average, precision) == 0, "ph_class_average.precision offset");
PH_ASSERT_LAYOUT(offsetof(ph_class_average, recall) == 8, "ph_class_average.recall offset");
PH_ASSERT_LAYOUT(offsetof(ph_class_average, f1) == 16, "ph_class_average.f1 offset");

PH_ASSERT_LAYOUT(sizeof(ph_classification_report) == 64, "ph_classification_report size");
PH_ASSERT_LAYOUT(_Alignof(ph_classification_report) == 8, "ph_classification_report alignment");
PH_ASSERT_LAYOUT(offsetof(ph_classification_report, accuracy) == 0, "ph_classification_report.accuracy offset");
PH_ASSERT_LAYOUT(offsetof(ph_classification_report, macro) == 8, "ph_classification_report.macro offset");
PH_ASSERT_LAYOUT(offsetof(ph_classification_report, weighted) == 32, "ph_classification_report.weighted offset");
PH_ASSERT_LAYOUT(offsetof(ph_classification_report, classes) == 56, "ph_classification_report.classes offset");

PH_ASSERT_LAYOUT(sizeof(ph_csv_options) == 16, "ph_csv_options size");
PH_ASSERT_LAYOUT(_Alignof(ph_csv_options) == 4, "ph_csv_options alignment");
PH_ASSERT_LAYOUT(offsetof(ph_csv_options, struct_size) == 0, "ph_csv_options.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_csv_options, delimiter) == 4, "ph_csv_options.delimiter offset");
PH_ASSERT_LAYOUT(offsetof(ph_csv_options, no_header) == 8, "ph_csv_options.no_header offset");
PH_ASSERT_LAYOUT(offsetof(ph_csv_options, keep_empty_lines) == 12, "ph_csv_options.keep_empty_lines offset");

PH_ASSERT_LAYOUT(sizeof(ph_margin) == 16, "ph_margin size");
PH_ASSERT_LAYOUT(_Alignof(ph_margin) == 4, "ph_margin alignment");
PH_ASSERT_LAYOUT(offsetof(ph_margin, top) == 0, "ph_margin.top offset");
PH_ASSERT_LAYOUT(offsetof(ph_margin, right) == 4, "ph_margin.right offset");
PH_ASSERT_LAYOUT(offsetof(ph_margin, bottom) == 8, "ph_margin.bottom offset");
PH_ASSERT_LAYOUT(offsetof(ph_margin, left) == 12, "ph_margin.left offset");

PH_ASSERT_LAYOUT(sizeof(ph_axis_desc) == 56, "ph_axis_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_axis_desc) == 8, "ph_axis_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, struct_size) == 0, "ph_axis_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, type) == 4, "ph_axis_desc.type offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, domain) == 8, "ph_axis_desc.domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, factors) == 24, "ph_axis_desc.factors offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, factor_count) == 32, "ph_axis_desc.factor_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, times) == 40, "ph_axis_desc.times offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, time_count) == 48, "ph_axis_desc.time_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, color) == 52, "ph_axis_desc.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_tick) == 24, "ph_tick size");
PH_ASSERT_LAYOUT(_Alignof(ph_tick) == 8, "ph_tick alignment");
PH_ASSERT_LAYOUT(offsetof(ph_tick, value) == 0, "ph_tick.value offset");
PH_ASSERT_LAYOUT(offsetof(ph_tick, label) == 8, "ph_tick.label offset");
PH_ASSERT_LAYOUT(offsetof(ph_tick, minor) == 16, "ph_tick.minor offset");
PH_ASSERT_LAYOUT(offsetof(ph_tick, grid) == 20, "ph_tick.grid offset");

PH_ASSERT_LAYOUT(sizeof(ph_axis_config) == 104, "ph_axis_config size");
PH_ASSERT_LAYOUT(_Alignof(ph_axis_config) == 8, "ph_axis_config alignment");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, struct_size) == 0, "ph_axis_config.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, no_axis_line) == 4, "ph_axis_config.no_axis_line offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, no_ticks) == 8, "ph_axis_config.no_ticks offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, no_grid) == 12, "ph_axis_config.no_grid offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, axis_line_color) == 16, "ph_axis_config.axis_line_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, axis_line_width) == 20, "ph_axis_config.axis_line_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, tick_color) == 24, "ph_axis_config.tick_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, tick_length) == 28, "ph_axis_config.tick_length offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, tick_width) == 32, "ph_axis_config.tick_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_color) == 36, "ph_axis_config.label_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_size) == 40, "ph_axis_config.label_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_rotation) == 44, "ph_axis_config.label_rotation offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_standoff) == 48, "ph_axis_config.label_standoff offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, title) == 56, "ph_axis_config.title offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, title_color) == 64, "ph_axis_config.title_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, title_size) == 68, "ph_axis_config.title_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_color) == 72, "ph_axis_config.grid_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_minor_color) == 76, "ph_axis_config.grid_minor_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_width) == 80, "ph_axis_config.grid_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_dash) == 88, "ph_axis_config.grid_dash offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_dash_count) == 96, "ph_axis_config.grid_dash_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, minor_ticks) == 100, "ph_axis_config.minor_ticks offset");

PH_ASSERT_LAYOUT(sizeof(ph_plot_desc) == 216, "ph_plot_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_plot_desc) == 8, "ph_plot_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, struct_size) == 0, "ph_plot_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, width) == 4, "ph_plot_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, height) == 8, "ph_plot_desc.height offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, theme) == 12, "ph_plot_desc.theme offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, margin) == 16, "ph_plot_desc.margin offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, x) == 32, "ph_plot_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, y) == 88, "ph_plot_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, background) == 144, "ph_plot_desc.background offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, border) == 148, "ph_plot_desc.border offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, title) == 152, "ph_plot_desc.title offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, mode) == 160, "ph_plot_desc.mode offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, pick) == 164, "ph_plot_desc.pick offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_interaction) == 168, "ph_plot_desc.no_interaction offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_hover) == 172, "ph_plot_desc.no_hover offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_crosshair) == 176, "ph_plot_desc.no_crosshair offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_tooltip) == 180, "ph_plot_desc.no_tooltip offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_colorbar) == 184, "ph_plot_desc.no_colorbar offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, equal_aspect) == 188, "ph_plot_desc.equal_aspect offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, bounded_pan) == 192, "ph_plot_desc.bounded_pan offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, legend) == 196, "ph_plot_desc.legend offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, legend_position) == 200, "ph_plot_desc.legend_position offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, legend_horizontal) == 204, "ph_plot_desc.legend_horizontal offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, legend_static) == 208, "ph_plot_desc.legend_static offset");

PH_ASSERT_LAYOUT(sizeof(ph_line_desc) == 96, "ph_line_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_line_desc) == 8, "ph_line_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, struct_size) == 0, "ph_line_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, x) == 8, "ph_line_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, y) == 16, "ph_line_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, count) == 24, "ph_line_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, color) == 28, "ph_line_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, width) == 32, "ph_line_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, name) == 40, "ph_line_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, y_axis) == 48, "ph_line_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, step) == 56, "ph_line_desc.step offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, join) == 60, "ph_line_desc.join offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, miter_limit) == 64, "ph_line_desc.miter_limit offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, dash) == 72, "ph_line_desc.dash offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, dash_count) == 80, "ph_line_desc.dash_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, no_decimate) == 84, "ph_line_desc.no_decimate offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, render_type) == 88, "ph_line_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_scatter_desc) == 120, "ph_scatter_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_scatter_desc) == 8, "ph_scatter_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, struct_size) == 0, "ph_scatter_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, x) == 8, "ph_scatter_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, y) == 16, "ph_scatter_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, count) == 24, "ph_scatter_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color) == 28, "ph_scatter_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, size) == 32, "ph_scatter_desc.size offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, sizes) == 40, "ph_scatter_desc.sizes offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, colors) == 48, "ph_scatter_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, marker) == 56, "ph_scatter_desc.marker offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, name) == 64, "ph_scatter_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, y_axis) == 72, "ph_scatter_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color_by) == 80, "ph_scatter_desc.color_by offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color_by_domain) == 88, "ph_scatter_desc.color_by_domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color_map) == 104, "ph_scatter_desc.color_map offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, render_type) == 112, "ph_scatter_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_area_desc) == 80, "ph_area_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_area_desc) == 8, "ph_area_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, struct_size) == 0, "ph_area_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, x) == 8, "ph_area_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, y) == 16, "ph_area_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, count) == 24, "ph_area_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, base) == 32, "ph_area_desc.base offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, base_value) == 40, "ph_area_desc.base_value offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, color) == 48, "ph_area_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, name) == 56, "ph_area_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, y_axis) == 64, "ph_area_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, render_type) == 72, "ph_area_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_bar_desc) == 104, "ph_bar_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_bar_desc) == 8, "ph_bar_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, struct_size) == 0, "ph_bar_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, x) == 8, "ph_bar_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, y) == 16, "ph_bar_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, count) == 24, "ph_bar_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, base) == 32, "ph_bar_desc.base offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, base_value) == 40, "ph_bar_desc.base_value offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, width) == 48, "ph_bar_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, offset) == 56, "ph_bar_desc.offset offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, orientation) == 64, "ph_bar_desc.orientation offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, color) == 68, "ph_bar_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, colors) == 72, "ph_bar_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, name) == 80, "ph_bar_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, y_axis) == 88, "ph_bar_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, render_type) == 96, "ph_bar_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_pie_desc) == 96, "ph_pie_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_pie_desc) == 8, "ph_pie_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, struct_size) == 0, "ph_pie_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, values) == 8, "ph_pie_desc.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, count) == 16, "ph_pie_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, colors) == 24, "ph_pie_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, center_x) == 32, "ph_pie_desc.center_x offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, center_y) == 40, "ph_pie_desc.center_y offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, radius) == 48, "ph_pie_desc.radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, inner_radius) == 56, "ph_pie_desc.inner_radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, start_angle) == 64, "ph_pie_desc.start_angle offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, name) == 72, "ph_pie_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, y_axis) == 80, "ph_pie_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, render_type) == 88, "ph_pie_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_stem_desc) == 80, "ph_stem_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_stem_desc) == 8, "ph_stem_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, struct_size) == 0, "ph_stem_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, x) == 8, "ph_stem_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, y) == 16, "ph_stem_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, count) == 24, "ph_stem_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, baseline) == 32, "ph_stem_desc.baseline offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, color) == 40, "ph_stem_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, width) == 44, "ph_stem_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, marker_size) == 48, "ph_stem_desc.marker_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, name) == 56, "ph_stem_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, y_axis) == 64, "ph_stem_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, render_type) == 72, "ph_stem_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_errorbar_desc) == 128, "ph_errorbar_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_errorbar_desc) == 8, "ph_errorbar_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, struct_size) == 0, "ph_errorbar_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, x) == 8, "ph_errorbar_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y) == 16, "ph_errorbar_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, count) == 24, "ph_errorbar_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err_array) == 32, "ph_errorbar_desc.y_err_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err) == 40, "ph_errorbar_desc.y_err offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err_low_array) == 48, "ph_errorbar_desc.y_err_low_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err_high_array) == 56, "ph_errorbar_desc.y_err_high_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, x_err_array) == 64, "ph_errorbar_desc.x_err_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, x_err) == 72, "ph_errorbar_desc.x_err offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, color) == 80, "ph_errorbar_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, width) == 84, "ph_errorbar_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, cap_size) == 88, "ph_errorbar_desc.cap_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, no_whiskers) == 92, "ph_errorbar_desc.no_whiskers offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, band) == 96, "ph_errorbar_desc.band offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, band_opacity) == 100, "ph_errorbar_desc.band_opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, name) == 104, "ph_errorbar_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_axis) == 112, "ph_errorbar_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, render_type) == 120, "ph_errorbar_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_box_group) == 32, "ph_box_group size");
PH_ASSERT_LAYOUT(_Alignof(ph_box_group) == 8, "ph_box_group alignment");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, position) == 0, "ph_box_group.position offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, values) == 8, "ph_box_group.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, count) == 16, "ph_box_group.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, color) == 20, "ph_box_group.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, label) == 24, "ph_box_group.label offset");

PH_ASSERT_LAYOUT(sizeof(ph_box_desc) == 64, "ph_box_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_box_desc) == 8, "ph_box_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, struct_size) == 0, "ph_box_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, groups) == 8, "ph_box_desc.groups offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, group_count) == 16, "ph_box_desc.group_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, width) == 24, "ph_box_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, no_box) == 32, "ph_box_desc.no_box offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, violin) == 36, "ph_box_desc.violin offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, name) == 40, "ph_box_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, y_axis) == 48, "ph_box_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, render_type) == 56, "ph_box_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_contour_desc) == 104, "ph_contour_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_contour_desc) == 8, "ph_contour_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, struct_size) == 0, "ph_contour_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, values) == 8, "ph_contour_desc.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, cols) == 16, "ph_contour_desc.cols offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, rows) == 20, "ph_contour_desc.rows offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, x) == 24, "ph_contour_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, y) == 40, "ph_contour_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, levels) == 56, "ph_contour_desc.levels offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, level_count) == 64, "ph_contour_desc.level_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, color) == 68, "ph_contour_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, colormap) == 72, "ph_contour_desc.colormap offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, name) == 80, "ph_contour_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, y_axis) == 88, "ph_contour_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_contour_desc, render_type) == 96, "ph_contour_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_edge) == 8, "ph_edge size");
PH_ASSERT_LAYOUT(_Alignof(ph_edge) == 4, "ph_edge alignment");
PH_ASSERT_LAYOUT(offsetof(ph_edge, a) == 0, "ph_edge.a offset");
PH_ASSERT_LAYOUT(offsetof(ph_edge, b) == 4, "ph_edge.b offset");

PH_ASSERT_LAYOUT(sizeof(ph_graph_desc) == 88, "ph_graph_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_graph_desc) == 8, "ph_graph_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, struct_size) == 0, "ph_graph_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, x) == 8, "ph_graph_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, y) == 16, "ph_graph_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, node_count) == 24, "ph_graph_desc.node_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, edges) == 32, "ph_graph_desc.edges offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, edge_count) == 40, "ph_graph_desc.edge_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, node_color) == 44, "ph_graph_desc.node_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, edge_color) == 48, "ph_graph_desc.edge_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, node_size) == 52, "ph_graph_desc.node_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, layout_iterations) == 56, "ph_graph_desc.layout_iterations offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, name) == 64, "ph_graph_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, y_axis) == 72, "ph_graph_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_graph_desc, render_type) == 80, "ph_graph_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_hexbin_desc) == 88, "ph_hexbin_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_hexbin_desc) == 8, "ph_hexbin_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, struct_size) == 0, "ph_hexbin_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, x) == 8, "ph_hexbin_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, y) == 16, "ph_hexbin_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, count) == 24, "ph_hexbin_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, radius) == 32, "ph_hexbin_desc.radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, colormap) == 40, "ph_hexbin_desc.colormap offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, domain) == 48, "ph_hexbin_desc.domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, name) == 64, "ph_hexbin_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, y_axis) == 72, "ph_hexbin_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_hexbin_desc, render_type) == 80, "ph_hexbin_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_quiver_desc) == 128, "ph_quiver_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_quiver_desc) == 8, "ph_quiver_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, struct_size) == 0, "ph_quiver_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, x) == 8, "ph_quiver_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, y) == 16, "ph_quiver_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, u) == 24, "ph_quiver_desc.u offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, v) == 32, "ph_quiver_desc.v offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, count) == 40, "ph_quiver_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, scale) == 48, "ph_quiver_desc.scale offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, color) == 56, "ph_quiver_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, width) == 60, "ph_quiver_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, head_size) == 64, "ph_quiver_desc.head_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, color_by) == 68, "ph_quiver_desc.color_by offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, color_values) == 72, "ph_quiver_desc.color_values offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, color_map) == 80, "ph_quiver_desc.color_map offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, color_domain) == 88, "ph_quiver_desc.color_domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, name) == 104, "ph_quiver_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, y_axis) == 112, "ph_quiver_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_quiver_desc, render_type) == 120, "ph_quiver_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_candlestick_desc) == 104, "ph_candlestick_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_candlestick_desc) == 8, "ph_candlestick_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, struct_size) == 0, "ph_candlestick_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, x) == 8, "ph_candlestick_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, open) == 16, "ph_candlestick_desc.open offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, high) == 24, "ph_candlestick_desc.high offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, low) == 32, "ph_candlestick_desc.low offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, close) == 40, "ph_candlestick_desc.close offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, count) == 48, "ph_candlestick_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, width) == 56, "ph_candlestick_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, up_color) == 64, "ph_candlestick_desc.up_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, down_color) == 68, "ph_candlestick_desc.down_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, wick_width) == 72, "ph_candlestick_desc.wick_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, name) == 80, "ph_candlestick_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, y_axis) == 88, "ph_candlestick_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_candlestick_desc, render_type) == 96, "ph_candlestick_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_ohlc_desc) == 104, "ph_ohlc_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_ohlc_desc) == 8, "ph_ohlc_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, struct_size) == 0, "ph_ohlc_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, x) == 8, "ph_ohlc_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, open) == 16, "ph_ohlc_desc.open offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, high) == 24, "ph_ohlc_desc.high offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, low) == 32, "ph_ohlc_desc.low offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, close) == 40, "ph_ohlc_desc.close offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, count) == 48, "ph_ohlc_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, width) == 56, "ph_ohlc_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, up_color) == 64, "ph_ohlc_desc.up_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, down_color) == 68, "ph_ohlc_desc.down_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, line_width) == 72, "ph_ohlc_desc.line_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, name) == 80, "ph_ohlc_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, y_axis) == 88, "ph_ohlc_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_ohlc_desc, render_type) == 96, "ph_ohlc_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_annotation) == 152, "ph_annotation size");
PH_ASSERT_LAYOUT(_Alignof(ph_annotation) == 8, "ph_annotation alignment");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, struct_size) == 0, "ph_annotation.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, type) == 4, "ph_annotation.type offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, dim) == 8, "ph_annotation.dim offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, x0) == 16, "ph_annotation.x0 offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, y0) == 24, "ph_annotation.y0 offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, x1) == 32, "ph_annotation.x1 offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, y1) == 40, "ph_annotation.y1 offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, high) == 48, "ph_annotation.high offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, low) == 56, "ph_annotation.low offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, ratios) == 64, "ph_annotation.ratios offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, ratio_count) == 72, "ph_annotation.ratio_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, color) == 76, "ph_annotation.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, border) == 80, "ph_annotation.border offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, width) == 84, "ph_annotation.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, dash) == 88, "ph_annotation.dash offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, dash_count) == 96, "ph_annotation.dash_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, label) == 104, "ph_annotation.label offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, text) == 112, "ph_annotation.text offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, dx) == 120, "ph_annotation.dx offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, dy) == 124, "ph_annotation.dy offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, align) == 128, "ph_annotation.align offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, baseline) == 132, "ph_annotation.baseline offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, size) == 136, "ph_annotation.size offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, fill) == 140, "ph_annotation.fill offset");
PH_ASSERT_LAYOUT(offsetof(ph_annotation, y_axis) == 144, "ph_annotation.y_axis offset");

PH_ASSERT_LAYOUT(sizeof(ph_legend_config) == 20, "ph_legend_config size");
PH_ASSERT_LAYOUT(_Alignof(ph_legend_config) == 4, "ph_legend_config alignment");
PH_ASSERT_LAYOUT(offsetof(ph_legend_config, struct_size) == 0, "ph_legend_config.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_legend_config, enabled) == 4, "ph_legend_config.enabled offset");
PH_ASSERT_LAYOUT(offsetof(ph_legend_config, position) == 8, "ph_legend_config.position offset");
PH_ASSERT_LAYOUT(offsetof(ph_legend_config, horizontal) == 12, "ph_legend_config.horizontal offset");
PH_ASSERT_LAYOUT(offsetof(ph_legend_config, no_toggle) == 16, "ph_legend_config.no_toggle offset");

PH_ASSERT_LAYOUT(sizeof(ph_heatmap_desc) == 112, "ph_heatmap_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_heatmap_desc) == 8, "ph_heatmap_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, struct_size) == 0, "ph_heatmap_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, values) == 8, "ph_heatmap_desc.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, cols) == 16, "ph_heatmap_desc.cols offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, rows) == 20, "ph_heatmap_desc.rows offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, x) == 24, "ph_heatmap_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, y) == 40, "ph_heatmap_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, colormap) == 56, "ph_heatmap_desc.colormap offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, domain) == 64, "ph_heatmap_desc.domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, no_smooth) == 80, "ph_heatmap_desc.no_smooth offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, name) == 88, "ph_heatmap_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, y_axis) == 96, "ph_heatmap_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_heatmap_desc, render_type) == 104, "ph_heatmap_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_image_desc) == 96, "ph_image_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_image_desc) == 8, "ph_image_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, struct_size) == 0, "ph_image_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, pixels) == 8, "ph_image_desc.pixels offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, width) == 16, "ph_image_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, height) == 20, "ph_image_desc.height offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, x) == 24, "ph_image_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, y) == 40, "ph_image_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, bottom_up) == 56, "ph_image_desc.bottom_up offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, no_smooth) == 60, "ph_image_desc.no_smooth offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, opacity) == 64, "ph_image_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, name) == 72, "ph_image_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, y_axis) == 80, "ph_image_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_image_desc, render_type) == 88, "ph_image_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_patch) == 40, "ph_patch size");
PH_ASSERT_LAYOUT(_Alignof(ph_patch) == 8, "ph_patch alignment");
PH_ASSERT_LAYOUT(offsetof(ph_patch, x) == 0, "ph_patch.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, y) == 8, "ph_patch.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, count) == 16, "ph_patch.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, holes) == 24, "ph_patch.holes offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, hole_count) == 32, "ph_patch.hole_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, color) == 36, "ph_patch.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_patches_desc) == 88, "ph_patches_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_patches_desc) == 8, "ph_patches_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, struct_size) == 0, "ph_patches_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, patches) == 8, "ph_patches_desc.patches offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, patch_count) == 16, "ph_patches_desc.patch_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, color) == 20, "ph_patches_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, opacity) == 24, "ph_patches_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, name) == 32, "ph_patches_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, y_axis) == 40, "ph_patches_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, render_type) == 48, "ph_patches_desc.render_type offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, values) == 56, "ph_patches_desc.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, colormap) == 64, "ph_patches_desc.colormap offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, domain) == 72, "ph_patches_desc.domain offset");

PH_ASSERT_LAYOUT(sizeof(ph_event) == 104, "ph_event size");
PH_ASSERT_LAYOUT(_Alignof(ph_event) == 8, "ph_event alignment");
PH_ASSERT_LAYOUT(offsetof(ph_event, struct_size) == 0, "ph_event.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, type) == 4, "ph_event.type offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, layer) == 8, "ph_event.layer offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, x) == 16, "ph_event.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, y) == 32, "ph_event.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, cursor_x) == 48, "ph_event.cursor_x offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, cursor_y) == 56, "ph_event.cursor_y offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, cursor_valid) == 64, "ph_event.cursor_valid offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, mode) == 68, "ph_event.mode offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, visible) == 72, "ph_event.visible offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, point_x) == 80, "ph_event.point_x offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, point_y) == 88, "ph_event.point_y offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, point_index) == 96, "ph_event.point_index offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, point_valid) == 100, "ph_event.point_valid offset");

PH_ASSERT_LAYOUT(sizeof(ph_title_config) == 32, "ph_title_config size");
PH_ASSERT_LAYOUT(_Alignof(ph_title_config) == 8, "ph_title_config alignment");
PH_ASSERT_LAYOUT(offsetof(ph_title_config, struct_size) == 0, "ph_title_config.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_title_config, text) == 8, "ph_title_config.text offset");
PH_ASSERT_LAYOUT(offsetof(ph_title_config, color) == 16, "ph_title_config.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_title_config, size) == 20, "ph_title_config.size offset");
PH_ASSERT_LAYOUT(offsetof(ph_title_config, align) == 24, "ph_title_config.align offset");

PH_ASSERT_LAYOUT(sizeof(ph_series) == 24, "ph_series size");
PH_ASSERT_LAYOUT(_Alignof(ph_series) == 8, "ph_series alignment");
PH_ASSERT_LAYOUT(offsetof(ph_series, y) == 0, "ph_series.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_series, color) == 8, "ph_series.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_series, name) == 16, "ph_series.name offset");

PH_ASSERT_LAYOUT(sizeof(ph_grouped_bar_desc) == 80, "ph_grouped_bar_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_grouped_bar_desc) == 8, "ph_grouped_bar_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, struct_size) == 0, "ph_grouped_bar_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, x) == 8, "ph_grouped_bar_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, count) == 16, "ph_grouped_bar_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, series) == 24, "ph_grouped_bar_desc.series offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, series_count) == 32, "ph_grouped_bar_desc.series_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, group_width) == 40, "ph_grouped_bar_desc.group_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, gap) == 48, "ph_grouped_bar_desc.gap offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, orientation) == 56, "ph_grouped_bar_desc.orientation offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, y_axis) == 64, "ph_grouped_bar_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_grouped_bar_desc, render_type) == 72, "ph_grouped_bar_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_stacked_desc) == 72, "ph_stacked_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_stacked_desc) == 8, "ph_stacked_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, struct_size) == 0, "ph_stacked_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, x) == 8, "ph_stacked_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, count) == 16, "ph_stacked_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, series) == 24, "ph_stacked_desc.series offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, series_count) == 32, "ph_stacked_desc.series_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, width) == 40, "ph_stacked_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, orientation) == 48, "ph_stacked_desc.orientation offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, y_axis) == 56, "ph_stacked_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_stacked_desc, render_type) == 64, "ph_stacked_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_histogram_desc) == 72, "ph_histogram_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_histogram_desc) == 8, "ph_histogram_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, struct_size) == 0, "ph_histogram_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, values) == 8, "ph_histogram_desc.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, count) == 16, "ph_histogram_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, bins) == 20, "ph_histogram_desc.bins offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, range) == 24, "ph_histogram_desc.range offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, color) == 40, "ph_histogram_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, name) == 48, "ph_histogram_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, y_axis) == 56, "ph_histogram_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_histogram_desc, render_type) == 64, "ph_histogram_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_spectrogram_desc) == 72, "ph_spectrogram_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_spectrogram_desc) == 8, "ph_spectrogram_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, struct_size) == 0, "ph_spectrogram_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, signal) == 8, "ph_spectrogram_desc.signal offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, count) == 16, "ph_spectrogram_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, fft_size) == 20, "ph_spectrogram_desc.fft_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, hop) == 24, "ph_spectrogram_desc.hop offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, sample_rate) == 32, "ph_spectrogram_desc.sample_rate offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, colormap) == 40, "ph_spectrogram_desc.colormap offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, name) == 48, "ph_spectrogram_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, y_axis) == 56, "ph_spectrogram_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_spectrogram_desc, render_type) == 64, "ph_spectrogram_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_chart_item) == 24, "ph_chart_item size");
PH_ASSERT_LAYOUT(_Alignof(ph_chart_item) == 8, "ph_chart_item alignment");
PH_ASSERT_LAYOUT(offsetof(ph_chart_item, label) == 0, "ph_chart_item.label offset");
PH_ASSERT_LAYOUT(offsetof(ph_chart_item, value) == 8, "ph_chart_item.value offset");
PH_ASSERT_LAYOUT(offsetof(ph_chart_item, color) == 16, "ph_chart_item.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_treemap_desc) == 88, "ph_treemap_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_treemap_desc) == 8, "ph_treemap_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, struct_size) == 0, "ph_treemap_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, items) == 8, "ph_treemap_desc.items offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, item_count) == 16, "ph_treemap_desc.item_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, x) == 24, "ph_treemap_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, y) == 40, "ph_treemap_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, palette) == 56, "ph_treemap_desc.palette offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, opacity) == 64, "ph_treemap_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, name) == 72, "ph_treemap_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, render_type) == 80, "ph_treemap_desc.render_type offset");
PH_ASSERT_LAYOUT(offsetof(ph_treemap_desc, no_labels) == 84, "ph_treemap_desc.no_labels offset");

PH_ASSERT_LAYOUT(sizeof(ph_funnel_desc) == 80, "ph_funnel_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_funnel_desc) == 8, "ph_funnel_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, struct_size) == 0, "ph_funnel_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, items) == 8, "ph_funnel_desc.items offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, item_count) == 16, "ph_funnel_desc.item_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, width) == 24, "ph_funnel_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, height) == 32, "ph_funnel_desc.height offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, neck) == 40, "ph_funnel_desc.neck offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, palette) == 48, "ph_funnel_desc.palette offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, opacity) == 56, "ph_funnel_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, name) == 64, "ph_funnel_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, render_type) == 72, "ph_funnel_desc.render_type offset");
PH_ASSERT_LAYOUT(offsetof(ph_funnel_desc, no_labels) == 76, "ph_funnel_desc.no_labels offset");

PH_ASSERT_LAYOUT(sizeof(ph_tree_node) == 32, "ph_tree_node size");
PH_ASSERT_LAYOUT(_Alignof(ph_tree_node) == 8, "ph_tree_node alignment");
PH_ASSERT_LAYOUT(offsetof(ph_tree_node, name) == 0, "ph_tree_node.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_tree_node, parent) == 8, "ph_tree_node.parent offset");
PH_ASSERT_LAYOUT(offsetof(ph_tree_node, value) == 16, "ph_tree_node.value offset");
PH_ASSERT_LAYOUT(offsetof(ph_tree_node, color) == 24, "ph_tree_node.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_sunburst_desc) == 80, "ph_sunburst_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_sunburst_desc) == 8, "ph_sunburst_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, struct_size) == 0, "ph_sunburst_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, nodes) == 8, "ph_sunburst_desc.nodes offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, node_count) == 16, "ph_sunburst_desc.node_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, ring_width) == 24, "ph_sunburst_desc.ring_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, center) == 32, "ph_sunburst_desc.center offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, start_angle) == 40, "ph_sunburst_desc.start_angle offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, palette) == 48, "ph_sunburst_desc.palette offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, opacity) == 56, "ph_sunburst_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, name) == 64, "ph_sunburst_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_sunburst_desc, render_type) == 72, "ph_sunburst_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_flow) == 16, "ph_flow size");
PH_ASSERT_LAYOUT(_Alignof(ph_flow) == 8, "ph_flow alignment");
PH_ASSERT_LAYOUT(offsetof(ph_flow, source) == 0, "ph_flow.source offset");
PH_ASSERT_LAYOUT(offsetof(ph_flow, target) == 4, "ph_flow.target offset");
PH_ASSERT_LAYOUT(offsetof(ph_flow, value) == 8, "ph_flow.value offset");

PH_ASSERT_LAYOUT(sizeof(ph_flow_node) == 16, "ph_flow_node size");
PH_ASSERT_LAYOUT(_Alignof(ph_flow_node) == 8, "ph_flow_node alignment");
PH_ASSERT_LAYOUT(offsetof(ph_flow_node, name) == 0, "ph_flow_node.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_flow_node, color) == 8, "ph_flow_node.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_sankey_desc) == 120, "ph_sankey_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_sankey_desc) == 8, "ph_sankey_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, struct_size) == 0, "ph_sankey_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, nodes) == 8, "ph_sankey_desc.nodes offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, node_count) == 16, "ph_sankey_desc.node_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, links) == 24, "ph_sankey_desc.links offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, link_count) == 32, "ph_sankey_desc.link_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, x) == 40, "ph_sankey_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, y) == 56, "ph_sankey_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, node_width) == 72, "ph_sankey_desc.node_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, node_padding) == 80, "ph_sankey_desc.node_padding offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, palette) == 88, "ph_sankey_desc.palette offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, opacity) == 96, "ph_sankey_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, ribbon_opacity) == 100, "ph_sankey_desc.ribbon_opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, name) == 104, "ph_sankey_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, render_type) == 112, "ph_sankey_desc.render_type offset");
PH_ASSERT_LAYOUT(offsetof(ph_sankey_desc, no_labels) == 116, "ph_sankey_desc.no_labels offset");

PH_ASSERT_LAYOUT(sizeof(ph_chord_desc) == 96, "ph_chord_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_chord_desc) == 8, "ph_chord_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, struct_size) == 0, "ph_chord_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, matrix) == 8, "ph_chord_desc.matrix offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, count) == 16, "ph_chord_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, labels) == 24, "ph_chord_desc.labels offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, label_count) == 32, "ph_chord_desc.label_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, radius) == 40, "ph_chord_desc.radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, pad_angle) == 48, "ph_chord_desc.pad_angle offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, arc_width) == 56, "ph_chord_desc.arc_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, palette) == 64, "ph_chord_desc.palette offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, ribbon_opacity) == 72, "ph_chord_desc.ribbon_opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, name) == 80, "ph_chord_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_chord_desc, render_type) == 88, "ph_chord_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_gauge_threshold) == 16, "ph_gauge_threshold size");
PH_ASSERT_LAYOUT(_Alignof(ph_gauge_threshold) == 8, "ph_gauge_threshold alignment");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_threshold, value) == 0, "ph_gauge_threshold.value offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_threshold, color) == 8, "ph_gauge_threshold.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_gauge_desc) == 120, "ph_gauge_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_gauge_desc) == 8, "ph_gauge_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, struct_size) == 0, "ph_gauge_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, value) == 8, "ph_gauge_desc.value offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, min) == 16, "ph_gauge_desc.min offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, max) == 24, "ph_gauge_desc.max offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, thresholds) == 32, "ph_gauge_desc.thresholds offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, threshold_count) == 40, "ph_gauge_desc.threshold_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, color) == 44, "ph_gauge_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, track_color) == 48, "ph_gauge_desc.track_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, needle_color) == 52, "ph_gauge_desc.needle_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, start_angle) == 56, "ph_gauge_desc.start_angle offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, end_angle) == 64, "ph_gauge_desc.end_angle offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, radius) == 72, "ph_gauge_desc.radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, inner_radius) == 80, "ph_gauge_desc.inner_radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, label) == 88, "ph_gauge_desc.label offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, no_label) == 96, "ph_gauge_desc.no_label offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, name) == 104, "ph_gauge_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_gauge_desc, render_type) == 112, "ph_gauge_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_parallel_desc) == 80, "ph_parallel_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_parallel_desc) == 8, "ph_parallel_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, struct_size) == 0, "ph_parallel_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, dimensions) == 8, "ph_parallel_desc.dimensions offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, dim_count) == 16, "ph_parallel_desc.dim_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, rows) == 24, "ph_parallel_desc.rows offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, row_count) == 32, "ph_parallel_desc.row_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, color_by) == 40, "ph_parallel_desc.color_by offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, palette) == 48, "ph_parallel_desc.palette offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, width) == 56, "ph_parallel_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, opacity) == 60, "ph_parallel_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, name) == 64, "ph_parallel_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, render_type) == 72, "ph_parallel_desc.render_type offset");
PH_ASSERT_LAYOUT(offsetof(ph_parallel_desc, no_axes) == 76, "ph_parallel_desc.no_axes offset");

#endif  /* 64-bit */

int main(void) {
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFu
  printf("%d struct layouts match the generated bindings\n", 66);
  return 0;
#else
  printf("SKIP: not a 64-bit target\n");
  return 77;
#endif
}
