/*
 * Generated by tools/generate_bindings.py from include/photon/photon.h.
 * Do not edit: regenerate instead.
 *
 * The C# and Java bindings place every field by an offset this generator
 * computed from its own model of the C type system. That model could be
 * wrong, and if it is, nothing in either language would say so — a struct
 * field read at the wrong offset is a plausible-looking number, not a
 * crash. So every offset the generator computed is asserted here against
 * what the compiler actually does, and this file is built as part of the
 * test suite. A wrong model fails the build here rather than corrupting a
 * descriptor in a host months later.
 */

#include <photon/photon.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

/* The rest of the suite builds as C99; this one file needs C11, for
 * _Static_assert and _Alignof. CMake asks for it. */
#if !defined(__STDC_VERSION__) || __STDC_VERSION__ < 201112L
#  error "abi_layout_test.c needs C11"
#endif
#define PH_ASSERT_LAYOUT(cond, message) _Static_assert(cond, message)

/* Every size below assumes a 64-bit target, which is what the bindings
 * assume too. A 32-bit build would need its own generated pair. */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFu

PH_ASSERT_LAYOUT(sizeof(ph_range) == 16, "ph_range size");
PH_ASSERT_LAYOUT(_Alignof(ph_range) == 8, "ph_range alignment");
PH_ASSERT_LAYOUT(offsetof(ph_range, lo) == 0, "ph_range.lo offset");
PH_ASSERT_LAYOUT(offsetof(ph_range, hi) == 8, "ph_range.hi offset");

PH_ASSERT_LAYOUT(sizeof(ph_host_desc) == 40, "ph_host_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_host_desc) == 8, "ph_host_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, struct_size) == 0, "ph_host_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, api) == 4, "ph_host_desc.api offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, get_proc_address) == 8, "ph_host_desc.get_proc_address offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, get_proc_address_user) == 16, "ph_host_desc.get_proc_address_user offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, log) == 24, "ph_host_desc.log offset");
PH_ASSERT_LAYOUT(offsetof(ph_host_desc, log_user) == 32, "ph_host_desc.log_user offset");

PH_ASSERT_LAYOUT(sizeof(ph_frame_target) == 32, "ph_frame_target size");
PH_ASSERT_LAYOUT(_Alignof(ph_frame_target) == 4, "ph_frame_target alignment");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, struct_size) == 0, "ph_frame_target.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, framebuffer) == 4, "ph_frame_target.framebuffer offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, x) == 8, "ph_frame_target.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, y) == 12, "ph_frame_target.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, width) == 16, "ph_frame_target.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, height) == 20, "ph_frame_target.height offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, dpr) == 24, "ph_frame_target.dpr offset");
PH_ASSERT_LAYOUT(offsetof(ph_frame_target, flip_y) == 28, "ph_frame_target.flip_y offset");

PH_ASSERT_LAYOUT(sizeof(ph_margin) == 16, "ph_margin size");
PH_ASSERT_LAYOUT(_Alignof(ph_margin) == 4, "ph_margin alignment");
PH_ASSERT_LAYOUT(offsetof(ph_margin, top) == 0, "ph_margin.top offset");
PH_ASSERT_LAYOUT(offsetof(ph_margin, right) == 4, "ph_margin.right offset");
PH_ASSERT_LAYOUT(offsetof(ph_margin, bottom) == 8, "ph_margin.bottom offset");
PH_ASSERT_LAYOUT(offsetof(ph_margin, left) == 12, "ph_margin.left offset");

PH_ASSERT_LAYOUT(sizeof(ph_axis_desc) == 56, "ph_axis_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_axis_desc) == 8, "ph_axis_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, struct_size) == 0, "ph_axis_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, type) == 4, "ph_axis_desc.type offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, domain) == 8, "ph_axis_desc.domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, factors) == 24, "ph_axis_desc.factors offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, factor_count) == 32, "ph_axis_desc.factor_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, times) == 40, "ph_axis_desc.times offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_desc, time_count) == 48, "ph_axis_desc.time_count offset");

PH_ASSERT_LAYOUT(sizeof(ph_tick) == 24, "ph_tick size");
PH_ASSERT_LAYOUT(_Alignof(ph_tick) == 8, "ph_tick alignment");
PH_ASSERT_LAYOUT(offsetof(ph_tick, value) == 0, "ph_tick.value offset");
PH_ASSERT_LAYOUT(offsetof(ph_tick, label) == 8, "ph_tick.label offset");
PH_ASSERT_LAYOUT(offsetof(ph_tick, minor) == 16, "ph_tick.minor offset");
PH_ASSERT_LAYOUT(offsetof(ph_tick, grid) == 20, "ph_tick.grid offset");

PH_ASSERT_LAYOUT(sizeof(ph_axis_config) == 104, "ph_axis_config size");
PH_ASSERT_LAYOUT(_Alignof(ph_axis_config) == 8, "ph_axis_config alignment");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, struct_size) == 0, "ph_axis_config.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, no_axis_line) == 4, "ph_axis_config.no_axis_line offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, no_ticks) == 8, "ph_axis_config.no_ticks offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, no_grid) == 12, "ph_axis_config.no_grid offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, axis_line_color) == 16, "ph_axis_config.axis_line_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, axis_line_width) == 20, "ph_axis_config.axis_line_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, tick_color) == 24, "ph_axis_config.tick_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, tick_length) == 28, "ph_axis_config.tick_length offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, tick_width) == 32, "ph_axis_config.tick_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_color) == 36, "ph_axis_config.label_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_size) == 40, "ph_axis_config.label_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_rotation) == 44, "ph_axis_config.label_rotation offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, label_standoff) == 48, "ph_axis_config.label_standoff offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, title) == 56, "ph_axis_config.title offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, title_color) == 64, "ph_axis_config.title_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, title_size) == 68, "ph_axis_config.title_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_color) == 72, "ph_axis_config.grid_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_minor_color) == 76, "ph_axis_config.grid_minor_color offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_width) == 80, "ph_axis_config.grid_width offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_dash) == 88, "ph_axis_config.grid_dash offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, grid_dash_count) == 96, "ph_axis_config.grid_dash_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_axis_config, minor_ticks) == 100, "ph_axis_config.minor_ticks offset");

PH_ASSERT_LAYOUT(sizeof(ph_plot_desc) == 200, "ph_plot_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_plot_desc) == 8, "ph_plot_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, struct_size) == 0, "ph_plot_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, width) == 4, "ph_plot_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, height) == 8, "ph_plot_desc.height offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, theme) == 12, "ph_plot_desc.theme offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, margin) == 16, "ph_plot_desc.margin offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, x) == 32, "ph_plot_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, y) == 88, "ph_plot_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, background) == 144, "ph_plot_desc.background offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, border) == 148, "ph_plot_desc.border offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, title) == 152, "ph_plot_desc.title offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, mode) == 160, "ph_plot_desc.mode offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, pick) == 164, "ph_plot_desc.pick offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_interaction) == 168, "ph_plot_desc.no_interaction offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_hover) == 172, "ph_plot_desc.no_hover offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_crosshair) == 176, "ph_plot_desc.no_crosshair offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, no_colorbar) == 180, "ph_plot_desc.no_colorbar offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, equal_aspect) == 184, "ph_plot_desc.equal_aspect offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, bounded_pan) == 188, "ph_plot_desc.bounded_pan offset");
PH_ASSERT_LAYOUT(offsetof(ph_plot_desc, legend) == 192, "ph_plot_desc.legend offset");

PH_ASSERT_LAYOUT(sizeof(ph_line_desc) == 96, "ph_line_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_line_desc) == 8, "ph_line_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, struct_size) == 0, "ph_line_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, x) == 8, "ph_line_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, y) == 16, "ph_line_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, count) == 24, "ph_line_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, color) == 28, "ph_line_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, width) == 32, "ph_line_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, name) == 40, "ph_line_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, y_axis) == 48, "ph_line_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, step) == 56, "ph_line_desc.step offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, join) == 60, "ph_line_desc.join offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, miter_limit) == 64, "ph_line_desc.miter_limit offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, dash) == 72, "ph_line_desc.dash offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, dash_count) == 80, "ph_line_desc.dash_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, no_decimate) == 84, "ph_line_desc.no_decimate offset");
PH_ASSERT_LAYOUT(offsetof(ph_line_desc, render_type) == 88, "ph_line_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_scatter_desc) == 112, "ph_scatter_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_scatter_desc) == 8, "ph_scatter_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, struct_size) == 0, "ph_scatter_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, x) == 8, "ph_scatter_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, y) == 16, "ph_scatter_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, count) == 24, "ph_scatter_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color) == 28, "ph_scatter_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, size) == 32, "ph_scatter_desc.size offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, sizes) == 40, "ph_scatter_desc.sizes offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, colors) == 48, "ph_scatter_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, marker) == 56, "ph_scatter_desc.marker offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, name) == 64, "ph_scatter_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, y_axis) == 72, "ph_scatter_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color_by) == 80, "ph_scatter_desc.color_by offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, color_by_domain) == 88, "ph_scatter_desc.color_by_domain offset");
PH_ASSERT_LAYOUT(offsetof(ph_scatter_desc, render_type) == 104, "ph_scatter_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_area_desc) == 80, "ph_area_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_area_desc) == 8, "ph_area_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, struct_size) == 0, "ph_area_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, x) == 8, "ph_area_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, y) == 16, "ph_area_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, count) == 24, "ph_area_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, base) == 32, "ph_area_desc.base offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, base_value) == 40, "ph_area_desc.base_value offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, color) == 48, "ph_area_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, name) == 56, "ph_area_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, y_axis) == 64, "ph_area_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_area_desc, render_type) == 72, "ph_area_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_bar_desc) == 104, "ph_bar_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_bar_desc) == 8, "ph_bar_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, struct_size) == 0, "ph_bar_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, x) == 8, "ph_bar_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, y) == 16, "ph_bar_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, count) == 24, "ph_bar_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, base) == 32, "ph_bar_desc.base offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, base_value) == 40, "ph_bar_desc.base_value offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, width) == 48, "ph_bar_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, offset) == 56, "ph_bar_desc.offset offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, orientation) == 64, "ph_bar_desc.orientation offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, color) == 68, "ph_bar_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, colors) == 72, "ph_bar_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, name) == 80, "ph_bar_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, y_axis) == 88, "ph_bar_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_bar_desc, render_type) == 96, "ph_bar_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_pie_desc) == 96, "ph_pie_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_pie_desc) == 8, "ph_pie_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, struct_size) == 0, "ph_pie_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, values) == 8, "ph_pie_desc.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, count) == 16, "ph_pie_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, colors) == 24, "ph_pie_desc.colors offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, center_x) == 32, "ph_pie_desc.center_x offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, center_y) == 40, "ph_pie_desc.center_y offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, radius) == 48, "ph_pie_desc.radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, inner_radius) == 56, "ph_pie_desc.inner_radius offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, start_angle) == 64, "ph_pie_desc.start_angle offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, name) == 72, "ph_pie_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, y_axis) == 80, "ph_pie_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_pie_desc, render_type) == 88, "ph_pie_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_stem_desc) == 80, "ph_stem_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_stem_desc) == 8, "ph_stem_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, struct_size) == 0, "ph_stem_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, x) == 8, "ph_stem_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, y) == 16, "ph_stem_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, count) == 24, "ph_stem_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, baseline) == 32, "ph_stem_desc.baseline offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, color) == 40, "ph_stem_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, width) == 44, "ph_stem_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, marker_size) == 48, "ph_stem_desc.marker_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, name) == 56, "ph_stem_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, y_axis) == 64, "ph_stem_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_stem_desc, render_type) == 72, "ph_stem_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_errorbar_desc) == 128, "ph_errorbar_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_errorbar_desc) == 8, "ph_errorbar_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, struct_size) == 0, "ph_errorbar_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, x) == 8, "ph_errorbar_desc.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y) == 16, "ph_errorbar_desc.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, count) == 24, "ph_errorbar_desc.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err_array) == 32, "ph_errorbar_desc.y_err_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err) == 40, "ph_errorbar_desc.y_err offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err_low_array) == 48, "ph_errorbar_desc.y_err_low_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_err_high_array) == 56, "ph_errorbar_desc.y_err_high_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, x_err_array) == 64, "ph_errorbar_desc.x_err_array offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, x_err) == 72, "ph_errorbar_desc.x_err offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, color) == 80, "ph_errorbar_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, width) == 84, "ph_errorbar_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, cap_size) == 88, "ph_errorbar_desc.cap_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, no_whiskers) == 92, "ph_errorbar_desc.no_whiskers offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, band) == 96, "ph_errorbar_desc.band offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, band_opacity) == 100, "ph_errorbar_desc.band_opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, name) == 104, "ph_errorbar_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, y_axis) == 112, "ph_errorbar_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_errorbar_desc, render_type) == 120, "ph_errorbar_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_box_group) == 32, "ph_box_group size");
PH_ASSERT_LAYOUT(_Alignof(ph_box_group) == 8, "ph_box_group alignment");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, position) == 0, "ph_box_group.position offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, values) == 8, "ph_box_group.values offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, count) == 16, "ph_box_group.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, color) == 20, "ph_box_group.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_group, label) == 24, "ph_box_group.label offset");

PH_ASSERT_LAYOUT(sizeof(ph_box_desc) == 64, "ph_box_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_box_desc) == 8, "ph_box_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, struct_size) == 0, "ph_box_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, groups) == 8, "ph_box_desc.groups offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, group_count) == 16, "ph_box_desc.group_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, width) == 24, "ph_box_desc.width offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, no_box) == 32, "ph_box_desc.no_box offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, violin) == 36, "ph_box_desc.violin offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, name) == 40, "ph_box_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, y_axis) == 48, "ph_box_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_box_desc, render_type) == 56, "ph_box_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_patch) == 40, "ph_patch size");
PH_ASSERT_LAYOUT(_Alignof(ph_patch) == 8, "ph_patch alignment");
PH_ASSERT_LAYOUT(offsetof(ph_patch, x) == 0, "ph_patch.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, y) == 8, "ph_patch.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, count) == 16, "ph_patch.count offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, holes) == 24, "ph_patch.holes offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, hole_count) == 32, "ph_patch.hole_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_patch, color) == 36, "ph_patch.color offset");

PH_ASSERT_LAYOUT(sizeof(ph_patches_desc) == 56, "ph_patches_desc size");
PH_ASSERT_LAYOUT(_Alignof(ph_patches_desc) == 8, "ph_patches_desc alignment");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, struct_size) == 0, "ph_patches_desc.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, patches) == 8, "ph_patches_desc.patches offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, patch_count) == 16, "ph_patches_desc.patch_count offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, color) == 20, "ph_patches_desc.color offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, opacity) == 24, "ph_patches_desc.opacity offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, name) == 32, "ph_patches_desc.name offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, y_axis) == 40, "ph_patches_desc.y_axis offset");
PH_ASSERT_LAYOUT(offsetof(ph_patches_desc, render_type) == 48, "ph_patches_desc.render_type offset");

PH_ASSERT_LAYOUT(sizeof(ph_event) == 80, "ph_event size");
PH_ASSERT_LAYOUT(_Alignof(ph_event) == 8, "ph_event alignment");
PH_ASSERT_LAYOUT(offsetof(ph_event, struct_size) == 0, "ph_event.struct_size offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, type) == 4, "ph_event.type offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, layer) == 8, "ph_event.layer offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, x) == 16, "ph_event.x offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, y) == 32, "ph_event.y offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, cursor_x) == 48, "ph_event.cursor_x offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, cursor_y) == 56, "ph_event.cursor_y offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, cursor_valid) == 64, "ph_event.cursor_valid offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, mode) == 68, "ph_event.mode offset");
PH_ASSERT_LAYOUT(offsetof(ph_event, visible) == 72, "ph_event.visible offset");

#endif  /* 64-bit */

int main(void) {
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFu
  printf("%d struct layouts match the generated bindings\n", 20);
  return 0;
#else
  printf("SKIP: not a 64-bit target\n");
  return 77;
#endif
}
