# Turn a binary file into a C++ translation unit holding it as a byte array.
#
# Run at build time via add_custom_command, so the repository stores one small
# .ttf rather than the ~180 KB of source text the same bytes cost as C literals.
# Regenerating is automatic: the custom command depends on the input file.
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -DNAMESPACE=<ns> \
#         -P embed_binary.cmake

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
  message(FATAL_ERROR "embed_binary.cmake needs INPUT, OUTPUT and SYMBOL")
endif()

file(READ "${INPUT}" HEXDATA HEX)
string(LENGTH "${HEXDATA}" HEXLEN)
math(EXPR BYTE_COUNT "${HEXLEN} / 2")
if(BYTE_COUNT EQUAL 0)
  message(FATAL_ERROR "embed_binary.cmake: ${INPUT} is empty")
endif()

# Two hex digits -> one 0xNN literal, then a newline every sixteen of them so the
# generated file stays something a person can open.
string(REGEX REPLACE "(..)" "0x\\1," BODY "${HEXDATA}")
string(REGEX REPLACE "((0x..,){16})" "\\1\n" BODY "${BODY}")

get_filename_component(INPUT_NAME "${INPUT}" NAME)

set(CONTENT "// Generated by cmake/embed_binary.cmake from ${INPUT_NAME}. Do not edit.\n")
string(APPEND CONTENT "#include <cstddef>\n\n")
if(NAMESPACE)
  string(APPEND CONTENT "namespace ${NAMESPACE} {\n\n")
endif()
string(APPEND CONTENT "extern const unsigned char ${SYMBOL}[];\n")
string(APPEND CONTENT "extern const std::size_t ${SYMBOL}_size;\n\n")
string(APPEND CONTENT "const unsigned char ${SYMBOL}[] = {\n${BODY}\n};\n")
string(APPEND CONTENT "const std::size_t ${SYMBOL}_size = ${BYTE_COUNT};\n")
if(NAMESPACE)
  string(APPEND CONTENT "\n}  // namespace ${NAMESPACE}\n")
endif()

file(WRITE "${OUTPUT}" "${CONTENT}")
