// <auto-generated>
//   Generated by tools/generate_bindings.py from include/photon/photon.h.
//   Do not edit: regenerate instead. Field order here is load-bearing —
//   a member out of place is silent data corruption, not a compile error.
// </auto-generated>

using System;
using System.Runtime.InteropServices;

namespace Photon.Native;

public static partial class Ph
{
    /// <summary>The shared library, without prefix or extension.</summary>
    public const string Library = "photon";

    /// <summary>
    ///   Mandatory. .NET defaults to StdCall on 32-bit Windows, and the
    ///   library is cdecl everywhere.
    /// </summary>
    private const CallingConvention Cc = CallingConvention.Cdecl;

    public const uint AbiVersion = 1;

    public const ulong PH_NULL_HANDLE = 0UL;
    public const int PH_COLOR_AUTO = 0;
    public const int PH_OK = 0;
    public const int PH_E_INVALID_HANDLE = -1;
    public const int PH_E_INVALID_ARGUMENT = -2;
    public const int PH_E_OUT_OF_MEMORY = -3;
    public const int PH_E_UNSUPPORTED = -4;
    public const int PH_E_NOT_INITIALIZED = -5;
    public const int PH_E_ABI_MISMATCH = -6;
    public const int PH_E_GL = -7;
    public const int PH_E_WRONG_THREAD = -8;
    public const int PH_E_INTERNAL = -9;
    public const int PH_SCALE_LINEAR = 0;
    public const int PH_SCALE_LOG = 1;
    public const int PH_SCALE_TIME = 2;
    public const int PH_SCALE_CATEGORICAL = 3;
    public const int PH_SCALE_ORDINAL_TIME = 4;
    public const int PH_MODE_PAN = 0;
    public const int PH_MODE_BOX = 1;
    public const int PH_MODE_BOX_X = 2;
    public const int PH_MODE_BOX_Y = 3;
    public const int PH_RENDER_STATIC = 0;
    public const int PH_RENDER_DYNAMIC = 1;
    public const int PH_JOIN_ROUND = 0;
    public const int PH_JOIN_MITER = 1;
    public const int PH_JOIN_BEVEL = 2;
    public const int PH_JOIN_BUTT = 3;
    public const int PH_STEP_NONE = 0;
    public const int PH_STEP_BEFORE = 1;
    public const int PH_STEP_AFTER = 2;
    public const int PH_STEP_CENTER = 3;
    public const int PH_MARKER_CIRCLE = 0;
    public const int PH_MARKER_SQUARE = 1;
    public const int PH_MARKER_TRIANGLE = 2;
    public const int PH_MARKER_DIAMOND = 3;
    public const int PH_MARKER_CROSS = 4;
    public const int PH_MARKER_PLUS = 5;
    public const int PH_PICK_X = 0;
    public const int PH_PICK_Y = 1;
    public const int PH_PICK_XY = 2;
    public const int PH_THEME_DARK = 0;
    public const int PH_THEME_LIGHT = 1;
    public const int PH_GFX_GL33 = 0;
    public const int PH_GFX_GLES30 = 1;
    public const int PH_LOG_ERROR = 0;
    public const int PH_LOG_WARN = 1;
    public const int PH_LOG_INFO = 2;
    public const int PH_LOG_DEBUG = 3;
    public const int PH_TOGGLE_DEFAULT = 0;
    public const int PH_TOGGLE_ON = 1;
    public const int PH_TOGGLE_OFF = -1;
    public const int PH_ORIENT_VERTICAL = 0;
    public const int PH_ORIENT_HORIZONTAL = 1;
    public const int PH_EVENT_NONE = 0;
    public const int PH_EVENT_VIEW_CHANGED = 1;
    public const int PH_EVENT_CURSOR_MOVED = 2;
    public const int PH_EVENT_MODE_CHANGED = 3;
    public const int PH_EVENT_LAYER_VISIBILITY = 4;
    public const int PH_EVENT_REDRAW_REQUESTED = 5;
    public const int PH_BUTTON_LEFT = 0;
    public const int PH_BUTTON_MIDDLE = 1;
    public const int PH_BUTTON_RIGHT = 2;
    public const int PH_MOD_NONE = 0;
    public const int PH_MOD_SHIFT = 1;
    public const int PH_MOD_CTRL = 2;
    public const int PH_MOD_ALT = 4;
    public const int PH_MOD_SUPER = 8;

    [UnmanagedFunctionPointer(Cc)]
    public delegate IntPtr PhProcAddressFn([MarshalAs(UnmanagedType.LPUTF8Str)] string name, IntPtr user);

    [UnmanagedFunctionPointer(Cc)]
    public delegate void PhLogFn(int level, [MarshalAs(UnmanagedType.LPUTF8Str)] string message, IntPtr user);

    /// <summary>ph_range — 16 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_range
    {
        /// <summary>offset 0</summary>
        public double lo;
        /// <summary>offset 8</summary>
        public double hi;
    }

    /// <summary>ph_host_desc — 40 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_host_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 4</summary>
        public int api;
        /// <summary>offset 8</summary>
        public IntPtr get_proc_address;
        /// <summary>offset 16</summary>
        public IntPtr get_proc_address_user;
        /// <summary>offset 24</summary>
        public IntPtr log;
        /// <summary>offset 32</summary>
        public IntPtr log_user;
    }

    /// <summary>ph_frame_target — 32 bytes, alignment 4.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_frame_target
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 4</summary>
        public uint framebuffer;
        /// <summary>offset 8</summary>
        public int x;
        /// <summary>offset 12</summary>
        public int y;
        /// <summary>offset 16</summary>
        public int width;
        /// <summary>offset 20</summary>
        public int height;
        /// <summary>offset 24</summary>
        public float dpr;
        /// <summary>offset 28</summary>
        public int flip_y;
    }

    /// <summary>ph_colormap_spec — 40 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_colormap_spec
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr name;
        /// <summary>offset 16</summary>
        public IntPtr stops;
        /// <summary>offset 24</summary>
        public int stop_count;
        /// <summary>offset 28</summary>
        public int reverse;
        /// <summary>offset 32</summary>
        public int discrete_steps;
    }

    /// <summary>ph_margin — 16 bytes, alignment 4.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_margin
    {
        /// <summary>offset 0</summary>
        public float top;
        /// <summary>offset 4</summary>
        public float right;
        /// <summary>offset 8</summary>
        public float bottom;
        /// <summary>offset 12</summary>
        public float left;
    }

    /// <summary>ph_axis_desc — 56 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_axis_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 4</summary>
        public int type;
        /// <summary>offset 8</summary>
        public ph_range domain;
        /// <summary>offset 24</summary>
        public IntPtr factors;
        /// <summary>offset 32</summary>
        public int factor_count;
        /// <summary>offset 40</summary>
        public IntPtr times;
        /// <summary>offset 48</summary>
        public int time_count;
    }

    /// <summary>ph_tick — 24 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_tick
    {
        /// <summary>offset 0</summary>
        public double value;
        /// <summary>offset 8</summary>
        public IntPtr label;
        /// <summary>offset 16</summary>
        public int minor;
        /// <summary>offset 20</summary>
        public int grid;
    }

    /// <summary>ph_axis_config — 104 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_axis_config
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 4</summary>
        public int no_axis_line;
        /// <summary>offset 8</summary>
        public int no_ticks;
        /// <summary>offset 12</summary>
        public int no_grid;
        /// <summary>offset 16</summary>
        public uint axis_line_color;
        /// <summary>offset 20</summary>
        public float axis_line_width;
        /// <summary>offset 24</summary>
        public uint tick_color;
        /// <summary>offset 28</summary>
        public float tick_length;
        /// <summary>offset 32</summary>
        public float tick_width;
        /// <summary>offset 36</summary>
        public uint label_color;
        /// <summary>offset 40</summary>
        public float label_size;
        /// <summary>offset 44</summary>
        public float label_rotation;
        /// <summary>offset 48</summary>
        public float label_standoff;
        /// <summary>offset 56</summary>
        public IntPtr title;
        /// <summary>offset 64</summary>
        public uint title_color;
        /// <summary>offset 68</summary>
        public float title_size;
        /// <summary>offset 72</summary>
        public uint grid_color;
        /// <summary>offset 76</summary>
        public uint grid_minor_color;
        /// <summary>offset 80</summary>
        public float grid_width;
        /// <summary>offset 88</summary>
        public IntPtr grid_dash;
        /// <summary>offset 96</summary>
        public int grid_dash_count;
        /// <summary>offset 100</summary>
        public int minor_ticks;
    }

    /// <summary>ph_plot_desc — 200 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_plot_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 4</summary>
        public int width;
        /// <summary>offset 8</summary>
        public int height;
        /// <summary>offset 12</summary>
        public int theme;
        /// <summary>offset 16</summary>
        public ph_margin margin;
        /// <summary>offset 32</summary>
        public ph_axis_desc x;
        /// <summary>offset 88</summary>
        public ph_axis_desc y;
        /// <summary>offset 144</summary>
        public uint background;
        /// <summary>offset 148</summary>
        public uint border;
        /// <summary>offset 152</summary>
        public IntPtr title;
        /// <summary>offset 160</summary>
        public int mode;
        /// <summary>offset 164</summary>
        public int pick;
        /// <summary>offset 168</summary>
        public int no_interaction;
        /// <summary>offset 172</summary>
        public int no_hover;
        /// <summary>offset 176</summary>
        public int no_crosshair;
        /// <summary>offset 180</summary>
        public int no_colorbar;
        /// <summary>offset 184</summary>
        public int equal_aspect;
        /// <summary>offset 188</summary>
        public int bounded_pan;
        /// <summary>offset 192</summary>
        public int legend;
    }

    /// <summary>ph_line_desc — 96 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_line_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr x;
        /// <summary>offset 16</summary>
        public IntPtr y;
        /// <summary>offset 24</summary>
        public int count;
        /// <summary>offset 28</summary>
        public uint color;
        /// <summary>offset 32</summary>
        public float width;
        /// <summary>offset 40</summary>
        public IntPtr name;
        /// <summary>offset 48</summary>
        public IntPtr y_axis;
        /// <summary>offset 56</summary>
        public int step;
        /// <summary>offset 60</summary>
        public int join;
        /// <summary>offset 64</summary>
        public float miter_limit;
        /// <summary>offset 72</summary>
        public IntPtr dash;
        /// <summary>offset 80</summary>
        public int dash_count;
        /// <summary>offset 84</summary>
        public int no_decimate;
        /// <summary>offset 88</summary>
        public int render_type;
    }

    /// <summary>ph_scatter_desc — 112 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_scatter_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr x;
        /// <summary>offset 16</summary>
        public IntPtr y;
        /// <summary>offset 24</summary>
        public int count;
        /// <summary>offset 28</summary>
        public uint color;
        /// <summary>offset 32</summary>
        public float size;
        /// <summary>offset 40</summary>
        public IntPtr sizes;
        /// <summary>offset 48</summary>
        public IntPtr colors;
        /// <summary>offset 56</summary>
        public int marker;
        /// <summary>offset 64</summary>
        public IntPtr name;
        /// <summary>offset 72</summary>
        public IntPtr y_axis;
        /// <summary>offset 80</summary>
        public IntPtr color_by;
        /// <summary>offset 88</summary>
        public ph_range color_by_domain;
        /// <summary>offset 104</summary>
        public int render_type;
    }

    /// <summary>ph_area_desc — 80 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_area_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr x;
        /// <summary>offset 16</summary>
        public IntPtr y;
        /// <summary>offset 24</summary>
        public int count;
        /// <summary>offset 32</summary>
        public IntPtr @base;
        /// <summary>offset 40</summary>
        public double base_value;
        /// <summary>offset 48</summary>
        public uint color;
        /// <summary>offset 56</summary>
        public IntPtr name;
        /// <summary>offset 64</summary>
        public IntPtr y_axis;
        /// <summary>offset 72</summary>
        public int render_type;
    }

    /// <summary>ph_bar_desc — 104 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_bar_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr x;
        /// <summary>offset 16</summary>
        public IntPtr y;
        /// <summary>offset 24</summary>
        public int count;
        /// <summary>offset 32</summary>
        public IntPtr @base;
        /// <summary>offset 40</summary>
        public double base_value;
        /// <summary>offset 48</summary>
        public double width;
        /// <summary>offset 56</summary>
        public double offset;
        /// <summary>offset 64</summary>
        public int orientation;
        /// <summary>offset 68</summary>
        public uint color;
        /// <summary>offset 72</summary>
        public IntPtr colors;
        /// <summary>offset 80</summary>
        public IntPtr name;
        /// <summary>offset 88</summary>
        public IntPtr y_axis;
        /// <summary>offset 96</summary>
        public int render_type;
    }

    /// <summary>ph_pie_desc — 96 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_pie_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr values;
        /// <summary>offset 16</summary>
        public int count;
        /// <summary>offset 24</summary>
        public IntPtr colors;
        /// <summary>offset 32</summary>
        public double center_x;
        /// <summary>offset 40</summary>
        public double center_y;
        /// <summary>offset 48</summary>
        public double radius;
        /// <summary>offset 56</summary>
        public double inner_radius;
        /// <summary>offset 64</summary>
        public double start_angle;
        /// <summary>offset 72</summary>
        public IntPtr name;
        /// <summary>offset 80</summary>
        public IntPtr y_axis;
        /// <summary>offset 88</summary>
        public int render_type;
    }

    /// <summary>ph_stem_desc — 80 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_stem_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr x;
        /// <summary>offset 16</summary>
        public IntPtr y;
        /// <summary>offset 24</summary>
        public int count;
        /// <summary>offset 32</summary>
        public double baseline;
        /// <summary>offset 40</summary>
        public uint color;
        /// <summary>offset 44</summary>
        public float width;
        /// <summary>offset 48</summary>
        public float marker_size;
        /// <summary>offset 56</summary>
        public IntPtr name;
        /// <summary>offset 64</summary>
        public IntPtr y_axis;
        /// <summary>offset 72</summary>
        public int render_type;
    }

    /// <summary>ph_errorbar_desc — 128 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_errorbar_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr x;
        /// <summary>offset 16</summary>
        public IntPtr y;
        /// <summary>offset 24</summary>
        public int count;
        /// <summary>offset 32</summary>
        public IntPtr y_err_array;
        /// <summary>offset 40</summary>
        public double y_err;
        /// <summary>offset 48</summary>
        public IntPtr y_err_low_array;
        /// <summary>offset 56</summary>
        public IntPtr y_err_high_array;
        /// <summary>offset 64</summary>
        public IntPtr x_err_array;
        /// <summary>offset 72</summary>
        public double x_err;
        /// <summary>offset 80</summary>
        public uint color;
        /// <summary>offset 84</summary>
        public float width;
        /// <summary>offset 88</summary>
        public float cap_size;
        /// <summary>offset 92</summary>
        public int no_whiskers;
        /// <summary>offset 96</summary>
        public int band;
        /// <summary>offset 100</summary>
        public float band_opacity;
        /// <summary>offset 104</summary>
        public IntPtr name;
        /// <summary>offset 112</summary>
        public IntPtr y_axis;
        /// <summary>offset 120</summary>
        public int render_type;
    }

    /// <summary>ph_box_group — 32 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_box_group
    {
        /// <summary>offset 0</summary>
        public double position;
        /// <summary>offset 8</summary>
        public IntPtr values;
        /// <summary>offset 16</summary>
        public int count;
        /// <summary>offset 20</summary>
        public uint color;
        /// <summary>offset 24</summary>
        public IntPtr label;
    }

    /// <summary>ph_box_desc — 64 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_box_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr groups;
        /// <summary>offset 16</summary>
        public int group_count;
        /// <summary>offset 24</summary>
        public double width;
        /// <summary>offset 32</summary>
        public int no_box;
        /// <summary>offset 36</summary>
        public int violin;
        /// <summary>offset 40</summary>
        public IntPtr name;
        /// <summary>offset 48</summary>
        public IntPtr y_axis;
        /// <summary>offset 56</summary>
        public int render_type;
    }

    /// <summary>ph_heatmap_desc — 112 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_heatmap_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr values;
        /// <summary>offset 16</summary>
        public int cols;
        /// <summary>offset 20</summary>
        public int rows;
        /// <summary>offset 24</summary>
        public ph_range x;
        /// <summary>offset 40</summary>
        public ph_range y;
        /// <summary>offset 56</summary>
        public IntPtr colormap;
        /// <summary>offset 64</summary>
        public ph_range domain;
        /// <summary>offset 80</summary>
        public int no_smooth;
        /// <summary>offset 88</summary>
        public IntPtr name;
        /// <summary>offset 96</summary>
        public IntPtr y_axis;
        /// <summary>offset 104</summary>
        public int render_type;
    }

    /// <summary>ph_image_desc — 96 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_image_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr pixels;
        /// <summary>offset 16</summary>
        public int width;
        /// <summary>offset 20</summary>
        public int height;
        /// <summary>offset 24</summary>
        public ph_range x;
        /// <summary>offset 40</summary>
        public ph_range y;
        /// <summary>offset 56</summary>
        public int bottom_up;
        /// <summary>offset 60</summary>
        public int no_smooth;
        /// <summary>offset 64</summary>
        public float opacity;
        /// <summary>offset 72</summary>
        public IntPtr name;
        /// <summary>offset 80</summary>
        public IntPtr y_axis;
        /// <summary>offset 88</summary>
        public int render_type;
    }

    /// <summary>ph_patch — 40 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_patch
    {
        /// <summary>offset 0</summary>
        public IntPtr x;
        /// <summary>offset 8</summary>
        public IntPtr y;
        /// <summary>offset 16</summary>
        public int count;
        /// <summary>offset 24</summary>
        public IntPtr holes;
        /// <summary>offset 32</summary>
        public int hole_count;
        /// <summary>offset 36</summary>
        public uint color;
    }

    /// <summary>ph_patches_desc — 56 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_patches_desc
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 8</summary>
        public IntPtr patches;
        /// <summary>offset 16</summary>
        public int patch_count;
        /// <summary>offset 20</summary>
        public uint color;
        /// <summary>offset 24</summary>
        public float opacity;
        /// <summary>offset 32</summary>
        public IntPtr name;
        /// <summary>offset 40</summary>
        public IntPtr y_axis;
        /// <summary>offset 48</summary>
        public int render_type;
    }

    /// <summary>ph_event — 80 bytes, alignment 8.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct ph_event
    {
        /// <summary>offset 0</summary>
        public uint struct_size;
        /// <summary>offset 4</summary>
        public int type;
        /// <summary>offset 8</summary>
        public ulong layer;
        /// <summary>offset 16</summary>
        public ph_range x;
        /// <summary>offset 32</summary>
        public ph_range y;
        /// <summary>offset 48</summary>
        public double cursor_x;
        /// <summary>offset 56</summary>
        public double cursor_y;
        /// <summary>offset 64</summary>
        public int cursor_valid;
        /// <summary>offset 68</summary>
        public int mode;
        /// <summary>offset 72</summary>
        public int visible;
    }

    /// <summary>
    ///   Every function in the ABI, by name — so a binding-level test can
    ///   assert it exercised all of them rather than merely intending to.
    /// </summary>
    public static readonly string[] EntryPoints = {
        "ph_colormap_spec_init",
        "ph_colormap_register",
        "ph_colormap_sample",
        "ph_colormap_count",
        "ph_colormap_name",
        "ph_symmetric_domain",
        "ph_palette_register",
        "ph_palette_count",
        "ph_palette_name",
        "ph_palette_color",
        "ph_abi_version",
        "ph_version",
        "ph_init",
        "ph_shutdown",
        "ph_last_error",
        "ph_color_parse",
        "ph_host_desc_init",
        "ph_frame_target_init",
        "ph_plot_desc_init",
        "ph_axis_desc_init",
        "ph_axis_config_init",
        "ph_line_desc_init",
        "ph_scatter_desc_init",
        "ph_patches_desc_init",
        "ph_area_desc_init",
        "ph_bar_desc_init",
        "ph_pie_desc_init",
        "ph_stem_desc_init",
        "ph_errorbar_desc_init",
        "ph_box_desc_init",
        "ph_heatmap_desc_init",
        "ph_image_desc_init",
        "ph_plot_create",
        "ph_plot_destroy",
        "ph_plot_valid",
        "ph_plot_set_size",
        "ph_plot_set_margin",
        "ph_plot_set_theme",
        "ph_plot_set_title",
        "ph_plot_set_scale",
        "ph_plot_set_domain",
        "ph_plot_get_domain",
        "ph_plot_add_y_axis",
        "ph_plot_remove_y_axis",
        "ph_plot_set_axis_config",
        "ph_plot_set_axis_ticks",
        "ph_plot_autoscale",
        "ph_plot_reset_view",
        "ph_plot_add_line",
        "ph_plot_add_scatter",
        "ph_plot_add_patches",
        "ph_plot_add_area",
        "ph_plot_add_bar",
        "ph_plot_add_pie",
        "ph_plot_add_stem",
        "ph_plot_add_errorbar",
        "ph_plot_add_box",
        "ph_plot_add_heatmap",
        "ph_plot_add_image",
        "ph_layer_set_xy",
        "ph_layer_set_visible",
        "ph_layer_valid",
        "ph_layer_bounds",
        "ph_layer_destroy",
        "ph_plot_set_mode",
        "ph_plot_get_mode",
        "ph_plot_pointer_down",
        "ph_plot_pointer_move",
        "ph_plot_pointer_up",
        "ph_plot_pointer_leave",
        "ph_plot_wheel",
        "ph_plot_pan_pixels",
        "ph_plot_zoom_around",
        "ph_plot_data_at_pixel",
        "ph_plot_pixel_at_data",
        "ph_plot_render",
        "ph_plot_render_pixels",
        "ph_plot_needs_redraw",
        "ph_plot_poll_event",
        "ph_plot_clear_events",
    };

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_colormap_spec_init")]
    public static extern void ph_colormap_spec_init(out ph_colormap_spec @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_colormap_register")]
    public static extern int ph_colormap_register([MarshalAs(UnmanagedType.LPUTF8Str)] string name, uint[] stops, int stop_count);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_colormap_sample")]
    public static extern int ph_colormap_sample(IntPtr spec, double t, out uint @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_colormap_sample")]
    public static extern int ph_colormap_sample(in ph_colormap_spec spec, double t, out uint @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_colormap_count")]
    public static extern int ph_colormap_count();

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_colormap_name")]
    public static extern IntPtr ph_colormap_name(int index);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_symmetric_domain")]
    public static extern int ph_symmetric_domain(double[] values, int count, double center, out ph_range @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_palette_register")]
    public static extern int ph_palette_register([MarshalAs(UnmanagedType.LPUTF8Str)] string name, uint[] colors, int count);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_palette_count")]
    public static extern int ph_palette_count();

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_palette_name")]
    public static extern IntPtr ph_palette_name(int index);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_palette_color")]
    public static extern uint ph_palette_color([MarshalAs(UnmanagedType.LPUTF8Str)] string name, int index);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_abi_version")]
    public static extern uint ph_abi_version();

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_version")]
    public static extern void ph_version(out int major, out int minor, out int patch);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_init")]
    public static extern int ph_init(uint abi_version, IntPtr desc);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_init")]
    public static extern int ph_init(uint abi_version, in ph_host_desc desc);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_shutdown")]
    public static extern void ph_shutdown();

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_last_error")]
    public static extern IntPtr ph_last_error();

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_color_parse")]
    public static extern int ph_color_parse([MarshalAs(UnmanagedType.LPUTF8Str)] string css, out uint @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_host_desc_init")]
    public static extern void ph_host_desc_init(out ph_host_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_frame_target_init")]
    public static extern void ph_frame_target_init(out ph_frame_target @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_desc_init")]
    public static extern void ph_plot_desc_init(out ph_plot_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_axis_desc_init")]
    public static extern void ph_axis_desc_init(out ph_axis_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_axis_config_init")]
    public static extern void ph_axis_config_init(out ph_axis_config @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_line_desc_init")]
    public static extern void ph_line_desc_init(out ph_line_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_scatter_desc_init")]
    public static extern void ph_scatter_desc_init(out ph_scatter_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_patches_desc_init")]
    public static extern void ph_patches_desc_init(out ph_patches_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_area_desc_init")]
    public static extern void ph_area_desc_init(out ph_area_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_bar_desc_init")]
    public static extern void ph_bar_desc_init(out ph_bar_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_pie_desc_init")]
    public static extern void ph_pie_desc_init(out ph_pie_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_stem_desc_init")]
    public static extern void ph_stem_desc_init(out ph_stem_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_errorbar_desc_init")]
    public static extern void ph_errorbar_desc_init(out ph_errorbar_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_box_desc_init")]
    public static extern void ph_box_desc_init(out ph_box_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_heatmap_desc_init")]
    public static extern void ph_heatmap_desc_init(out ph_heatmap_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_image_desc_init")]
    public static extern void ph_image_desc_init(out ph_image_desc @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_create")]
    public static extern int ph_plot_create(IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_create")]
    public static extern int ph_plot_create(in ph_plot_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_destroy")]
    public static extern int ph_plot_destroy(ulong plot);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_valid")]
    public static extern int ph_plot_valid(ulong plot);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_size")]
    public static extern int ph_plot_set_size(ulong plot, int width, int height);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_margin")]
    public static extern int ph_plot_set_margin(ulong plot, IntPtr margin);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_margin")]
    public static extern int ph_plot_set_margin(ulong plot, in ph_margin margin);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_theme")]
    public static extern int ph_plot_set_theme(ulong plot, int theme);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_title")]
    public static extern int ph_plot_set_title(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string title);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_scale")]
    public static extern int ph_plot_set_scale(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, IntPtr desc);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_scale")]
    public static extern int ph_plot_set_scale(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, in ph_axis_desc desc);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_domain")]
    public static extern int ph_plot_set_domain(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, ph_range domain);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_get_domain")]
    public static extern int ph_plot_get_domain(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, out ph_range @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_y_axis")]
    public static extern int ph_plot_add_y_axis(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string id, IntPtr desc, int side);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_y_axis")]
    public static extern int ph_plot_add_y_axis(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string id, in ph_axis_desc desc, int side);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_remove_y_axis")]
    public static extern int ph_plot_remove_y_axis(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string id);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_axis_config")]
    public static extern int ph_plot_set_axis_config(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, IntPtr desc);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_axis_config")]
    public static extern int ph_plot_set_axis_config(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, in ph_axis_config desc);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_axis_ticks")]
    public static extern int ph_plot_set_axis_ticks(ulong plot, [MarshalAs(UnmanagedType.LPUTF8Str)] string axis, ph_tick[] ticks, int count);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_autoscale")]
    public static extern int ph_plot_autoscale(ulong plot);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_reset_view")]
    public static extern int ph_plot_reset_view(ulong plot);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_line")]
    public static extern int ph_plot_add_line(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_line")]
    public static extern int ph_plot_add_line(ulong plot, in ph_line_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_scatter")]
    public static extern int ph_plot_add_scatter(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_scatter")]
    public static extern int ph_plot_add_scatter(ulong plot, in ph_scatter_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_patches")]
    public static extern int ph_plot_add_patches(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_patches")]
    public static extern int ph_plot_add_patches(ulong plot, in ph_patches_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_area")]
    public static extern int ph_plot_add_area(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_area")]
    public static extern int ph_plot_add_area(ulong plot, in ph_area_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_bar")]
    public static extern int ph_plot_add_bar(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_bar")]
    public static extern int ph_plot_add_bar(ulong plot, in ph_bar_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_pie")]
    public static extern int ph_plot_add_pie(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_pie")]
    public static extern int ph_plot_add_pie(ulong plot, in ph_pie_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_stem")]
    public static extern int ph_plot_add_stem(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_stem")]
    public static extern int ph_plot_add_stem(ulong plot, in ph_stem_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_errorbar")]
    public static extern int ph_plot_add_errorbar(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_errorbar")]
    public static extern int ph_plot_add_errorbar(ulong plot, in ph_errorbar_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_box")]
    public static extern int ph_plot_add_box(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_box")]
    public static extern int ph_plot_add_box(ulong plot, in ph_box_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_heatmap")]
    public static extern int ph_plot_add_heatmap(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_heatmap")]
    public static extern int ph_plot_add_heatmap(ulong plot, in ph_heatmap_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_image")]
    public static extern int ph_plot_add_image(ulong plot, IntPtr desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_add_image")]
    public static extern int ph_plot_add_image(ulong plot, in ph_image_desc desc, out ulong @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_layer_set_xy")]
    public static extern int ph_layer_set_xy(ulong layer, double[] x, double[] y, int count);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_layer_set_visible")]
    public static extern int ph_layer_set_visible(ulong layer, int visible);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_layer_valid")]
    public static extern int ph_layer_valid(ulong layer);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_layer_bounds")]
    public static extern int ph_layer_bounds(ulong layer, out ph_range x, out ph_range y);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_layer_destroy")]
    public static extern int ph_layer_destroy(ulong layer);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_set_mode")]
    public static extern int ph_plot_set_mode(ulong plot, int mode);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_get_mode")]
    public static extern int ph_plot_get_mode(ulong plot, out int @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_pointer_down")]
    public static extern int ph_plot_pointer_down(ulong plot, double px, double py, int button, int mods);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_pointer_move")]
    public static extern int ph_plot_pointer_move(ulong plot, double px, double py, int mods);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_pointer_up")]
    public static extern int ph_plot_pointer_up(ulong plot, double px, double py, int button, int mods);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_pointer_leave")]
    public static extern int ph_plot_pointer_leave(ulong plot);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_wheel")]
    public static extern int ph_plot_wheel(ulong plot, double px, double py, double delta_y, int mods);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_pan_pixels")]
    public static extern int ph_plot_pan_pixels(ulong plot, double dx, double dy);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_zoom_around")]
    public static extern int ph_plot_zoom_around(ulong plot, double nx, double ny, double factor);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_data_at_pixel")]
    public static extern int ph_plot_data_at_pixel(ulong plot, double px, double py, out double out_x, out double out_y);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_pixel_at_data")]
    public static extern int ph_plot_pixel_at_data(ulong plot, double x, double y, out double out_px, out double out_py);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_render")]
    public static extern int ph_plot_render(ulong plot, IntPtr target);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_render")]
    public static extern int ph_plot_render(ulong plot, in ph_frame_target target);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_render_pixels")]
    public static extern int ph_plot_render_pixels(ulong plot, int width, int height, float dpr, byte[] out_rgba, int stride_bytes);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_needs_redraw")]
    public static extern int ph_plot_needs_redraw(ulong plot);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_poll_event")]
    public static extern int ph_plot_poll_event(ulong plot, out ph_event @out);

    [DllImport(Library, CallingConvention = Cc, EntryPoint = "ph_plot_clear_events")]
    public static extern int ph_plot_clear_events(ulong plot);

}
