<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { Plot as CorePlot, linkX } from "@photonviz/core";
  import { rsi, macd, firstFinite } from "@photonviz/svelte";
  import FsButton from "./FsButton.svelte";

  // Synthetic OHLC + session times, generated by the parent (deterministic).
  export let times: number[];
  export let idx: Float64Array;
  export let open: Float64Array;
  export let high: Float64Array;
  export let low: Float64Array;
  export let close: Float64Array;

  let priceNode: HTMLDivElement;
  let rsiNode: HTMLDivElement;
  let macdNode: HTMLDivElement;
  const plots: CorePlot[] = [];

  onMount(() => {
    /** Slice a series past its warm-up NaNs (indicators return leading NaN). */
    const trim = (y: Float64Array): { x: Float64Array; y: Float64Array } => {
      const s = Math.max(0, firstFinite(y));
      return { x: idx.subarray(s), y: y.subarray(s) };
    };

    const ord = { type: "ordinal-time" as const, times };

    const priceP = new CorePlot(priceNode, { theme: "dark", scales: { x: ord }, showToolbar: false });
    priceP.addCandlestick({ x: idx, open, high, low, close });
    priceP.render();

    const rsiP = new CorePlot(rsiNode, { theme: "dark", scales: { x: ord, y: { domain: [0, 100] } }, showToolbar: false });
    const r = trim(rsi(close, 14));
    rsiP.addLine({ x: r.x, y: r.y, color: "#f472b6", width: 1.5, name: "RSI" });
    rsiP.addAnnotation({ type: "span", dim: "y", value: 70, color: "#475569", dash: [4, 4] });
    rsiP.addAnnotation({ type: "span", dim: "y", value: 30, color: "#475569", dash: [4, 4] });
    rsiP.render();

    const m = macd(close, 12, 26, 9);
    const macdP = new CorePlot(macdNode, { theme: "dark", scales: { x: ord }, showToolbar: false });
    const hist = trim(m.histogram);
    macdP.addBar({ x: hist.x, y: hist.y, width: 0.7, color: "#64748b" });
    const ml = trim(m.macd), sl = trim(m.signal);
    macdP.addLine({ x: ml.x, y: ml.y, color: "#60a5fa", width: 1.5, name: "MACD" });
    macdP.addLine({ x: sl.x, y: sl.y, color: "#f59e0b", width: 1.5, name: "signal" });
    macdP.render();

    // Pan/zoom on any pane drives all three.
    linkX([priceP, rsiP, macdP]);
    plots.push(priceP, rsiP, macdP);
  });

  onDestroy(() => {
    for (const p of plots) p.destroy();
  });
</script>

<section class="card wide">
  <FsButton />
  <h2>Linked dashboard<span> — price · RSI(14) · MACD(12/26/9) · linkX</span></h2>
  <div class="chart" bind:this={priceNode}></div>
  <div class="chart chart--short" bind:this={rsiNode}></div>
  <div class="chart chart--short" bind:this={macdNode}></div>
</section>

<style>
  .chart--short {
    height: 130px;
  }
</style>
